[M::main::10.605*0.93] loaded/built the index for 3268 target sequence(s)
[M::mm_mapopt_update::13.936*0.95] mid_occ = 418
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3268
[M::mm_idx_stat::15.206*0.95] distinct minimizers: 98357046 (40.81% are singletons); average occurrences: 4.579; average spacing: 5.353; total length: 2410976875
[M::worker_pipeline::302.812*2.88] mapped 96513 sequences
[M::worker_pipeline::576.859*2.96] mapped 92403 sequences
[M::worker_pipeline::845.210*2.99] mapped 92425 sequences
[M::worker_pipeline::1112.259*3.01] mapped 92168 sequences
[M::worker_pipeline::1384.531*3.01] mapped 91650 sequences
[M::worker_pipeline::1652.712*3.02] mapped 91982 sequences
[M::worker_pipeline::1926.093*3.02] mapped 98433 sequences
[M::worker_pipeline::2200.031*3.03] mapped 90765 sequences
[M::worker_pipeline::2469.117*3.03] mapped 90980 sequences
[M::worker_pipeline::2730.820*3.03] mapped 94290 sequences
[M::worker_pipeline::2993.277*3.04] mapped 91011 sequences
[M::worker_pipeline::3255.607*3.04] mapped 90098 sequences
[M::worker_pipeline::3513.265*3.04] mapped 90285 sequences
[M::worker_pipeline::3780.773*3.04] mapped 96482 sequences
[M::worker_pipeline::4048.371*3.04] mapped 89640 sequences
[M::worker_pipeline::4314.156*3.04] mapped 89624 sequences
[M::worker_pipeline::4584.846*3.04] mapped 89240 sequences
[M::worker_pipeline::4843.729*3.04] mapped 89350 sequences
[M::worker_pipeline::5112.335*3.04] mapped 89367 sequences
[M::worker_pipeline::5376.631*3.04] mapped 95857 sequences
[M::worker_pipeline::5646.429*3.04] mapped 88400 sequences
[M::worker_pipeline::5913.212*3.04] mapped 88725 sequences
[M::worker_pipeline::6192.042*3.05] mapped 88680 sequences
[M::worker_pipeline::6469.832*3.05] mapped 88283 sequences
[M::worker_pipeline::6742.030*3.05] mapped 88250 sequences
[M::worker_pipeline::7011.008*3.05] mapped 93468 sequences
[M::worker_pipeline::7285.563*3.05] mapped 87974 sequences
[M::worker_pipeline::7560.195*3.05] mapped 87709 sequences
[M::worker_pipeline::7831.005*3.05] mapped 87861 sequences
[M::worker_pipeline::8104.147*3.05] mapped 88569 sequences
[M::worker_pipeline::8376.937*3.05] mapped 87467 sequences
[M::worker_pipeline::8658.377*3.05] mapped 93131 sequences
[M::worker_pipeline::8930.573*3.05] mapped 86560 sequences
[M::worker_pipeline::9200.217*3.05] mapped 86674 sequences
[M::worker_pipeline::9481.126*3.05] mapped 86570 sequences
[M::worker_pipeline::9754.327*3.05] mapped 87512 sequences
[M::worker_pipeline::10026.303*3.05] mapped 91357 sequences
[M::worker_pipeline::10304.977*3.05] mapped 86596 sequences
[M::worker_pipeline::10569.612*3.05] mapped 87201 sequences
[M::worker_pipeline::10838.679*3.05] mapped 87079 sequences
[M::worker_pipeline::11101.373*3.05] mapped 86507 sequences
[M::worker_pipeline::11372.219*3.05] mapped 90929 sequences
[M::worker_pipeline::11643.827*3.05] mapped 86649 sequences
[M::worker_pipeline::11904.844*3.05] mapped 86759 sequences
[M::worker_pipeline::12174.870*3.05] mapped 85989 sequences
[M::worker_pipeline::12436.163*3.05] mapped 90057 sequences
[M::worker_pipeline::12708.546*3.05] mapped 85678 sequences
[M::worker_pipeline::12973.927*3.05] mapped 85833 sequences
[M::worker_pipeline::13240.339*3.05] mapped 86001 sequences
[M::worker_pipeline::13508.556*3.05] mapped 90234 sequences
[M::worker_pipeline::13764.608*3.05] mapped 86245 sequences
[M::worker_pipeline::14024.387*3.05] mapped 85699 sequences
[M::worker_pipeline::14291.366*3.05] mapped 86325 sequences
[M::worker_pipeline::14556.863*3.05] mapped 89455 sequences
[M::worker_pipeline::14815.654*3.05] mapped 86078 sequences
[M::worker_pipeline::15071.917*3.05] mapped 85906 sequences
[M::worker_pipeline::15331.132*3.05] mapped 89017 sequences
[M::worker_pipeline::15592.290*3.05] mapped 85111 sequences
[M::worker_pipeline::15856.251*3.05] mapped 85294 sequences
[M::worker_pipeline::16122.742*3.05] mapped 87204 sequences
[M::worker_pipeline::16396.706*3.05] mapped 84530 sequences
[M::worker_pipeline::16666.301*3.05] mapped 84088 sequences
[M::worker_pipeline::16940.842*3.05] mapped 88146 sequences
[M::worker_pipeline::17206.209*3.05] mapped 85707 sequences
[M::worker_pipeline::17475.343*3.05] mapped 85296 sequences
[M::worker_pipeline::17744.598*3.05] mapped 88025 sequences
[M::worker_pipeline::18014.593*3.05] mapped 86413 sequences
[M::worker_pipeline::18287.107*3.05] mapped 88515 sequences
[M::worker_pipeline::18556.016*3.05] mapped 86676 sequences
[M::worker_pipeline::18825.302*3.05] mapped 89117 sequences
[M::worker_pipeline::19097.482*3.05] mapped 86475 sequences
[M::worker_pipeline::19368.449*3.05] mapped 88150 sequences
[M::worker_pipeline::19639.591*3.05] mapped 87146 sequences
[M::worker_pipeline::19904.787*3.05] mapped 88501 sequences
[M::worker_pipeline::20169.482*3.05] mapped 88852 sequences
[M::worker_pipeline::20435.324*3.05] mapped 89334 sequences
[M::worker_pipeline::20700.240*3.05] mapped 92226 sequences
[M::worker_pipeline::20957.340*3.05] mapped 93155 sequences
[M::worker_pipeline::21224.261*3.05] mapped 89450 sequences
[M::worker_pipeline::21491.347*3.05] mapped 90503 sequences
[M::worker_pipeline::21750.274*3.05] mapped 89362 sequences
[M::worker_pipeline::22012.301*3.05] mapped 88735 sequences
[M::worker_pipeline::22283.544*3.05] mapped 88403 sequences
[M::worker_pipeline::22552.280*3.05] mapped 89369 sequences
[M::worker_pipeline::22794.318*3.05] mapped 80326 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -a out/minimap/Canis_familiaris.mmi data/raw_data/nanopore/D-92-01.fastq.gz
[M::main] Real time: 22795.241 sec; CPU: 69550.011 sec; Peak RSS: 10.849 GB
[E::bam_write1] Positional data is too large for BAM format
[E::bam_write1] Positional data is too large for BAM format
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
