[M::main::10.721*0.87] loaded/built the index for 3268 target sequence(s)
[M::mm_mapopt_update::13.510*0.90] mid_occ = 418
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3268
[M::mm_idx_stat::15.023*0.91] distinct minimizers: 98357046 (40.81% are singletons); average occurrences: 4.579; average spacing: 5.353; total length: 2410976875
[M::worker_pipeline::281.340*2.87] mapped 99438 sequences
[M::worker_pipeline::532.376*2.96] mapped 98026 sequences
[M::worker_pipeline::799.423*2.99] mapped 94091 sequences
[M::worker_pipeline::1052.361*3.01] mapped 93674 sequences
[M::worker_pipeline::1303.978*3.02] mapped 93252 sequences
[M::worker_pipeline::1542.187*3.02] mapped 96415 sequences
[M::worker_pipeline::1794.495*3.03] mapped 91760 sequences
[M::worker_pipeline::2047.838*3.03] mapped 92041 sequences
[M::worker_pipeline::2302.884*3.04] mapped 91372 sequences
[M::worker_pipeline::2553.581*3.04] mapped 95071 sequences
[M::worker_pipeline::2807.512*3.04] mapped 90641 sequences
[M::worker_pipeline::3063.718*3.04] mapped 90521 sequences
[M::worker_pipeline::3312.979*3.04] mapped 89719 sequences
[M::worker_pipeline::3563.029*3.04] mapped 91626 sequences
[M::worker_pipeline::3819.537*3.04] mapped 88555 sequences
[M::worker_pipeline::4053.297*3.05] mapped 89738 sequences
[M::worker_pipeline::4304.825*3.05] mapped 89653 sequences
[M::worker_pipeline::4552.199*3.05] mapped 87661 sequences
[M::worker_pipeline::4789.671*3.05] mapped 90203 sequences
[M::worker_pipeline::5016.462*3.05] mapped 88896 sequences
[M::worker_pipeline::5244.047*3.05] mapped 89618 sequences
[M::worker_pipeline::5469.275*3.05] mapped 87828 sequences
[M::worker_pipeline::5701.467*3.05] mapped 89131 sequences
[M::worker_pipeline::5934.362*3.05] mapped 86839 sequences
[M::worker_pipeline::6178.386*3.05] mapped 87535 sequences
[M::worker_pipeline::6423.960*3.05] mapped 87875 sequences
[M::worker_pipeline::6675.064*3.05] mapped 87350 sequences
[M::worker_pipeline::6922.268*3.05] mapped 86611 sequences
[M::worker_pipeline::7176.180*3.05] mapped 84757 sequences
[M::worker_pipeline::7423.730*3.05] mapped 85792 sequences
[M::worker_pipeline::7671.264*3.05] mapped 84560 sequences
[M::worker_pipeline::7902.783*3.05] mapped 84649 sequences
[M::worker_pipeline::8148.479*3.05] mapped 86127 sequences
[M::worker_pipeline::8380.661*3.05] mapped 86497 sequences
[M::worker_pipeline::8617.134*3.05] mapped 86527 sequences
[M::worker_pipeline::8854.043*3.05] mapped 87642 sequences
[M::worker_pipeline::9109.303*3.05] mapped 93555 sequences
[M::worker_pipeline::9371.384*3.05] mapped 101400 sequences
[M::worker_pipeline::9639.753*3.05] mapped 96771 sequences
[M::worker_pipeline::9911.875*3.05] mapped 96570 sequences
[M::worker_pipeline::10172.355*3.05] mapped 95851 sequences
[M::worker_pipeline::10255.501*3.05] mapped 31760 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -a out/minimap/Canis_familiaris.mmi data/raw_data/nanopore/D-85-02.fastq.gz
[M::main] Real time: 10256.475 sec; CPU: 31291.307 sec; Peak RSS: 10.808 GB
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
