[M::main::10.704*0.80] loaded/built the index for 3268 target sequence(s)
[M::mm_mapopt_update::13.999*0.84] mid_occ = 418
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3268
[M::mm_idx_stat::14.914*0.85] distinct minimizers: 98357046 (40.81% are singletons); average occurrences: 4.579; average spacing: 5.353; total length: 2410976875
[M::worker_pipeline::226.771*2.84] mapped 78957 sequences
[M::worker_pipeline::427.105*2.94] mapped 74871 sequences
[M::worker_pipeline::630.187*2.98] mapped 80807 sequences
[M::worker_pipeline::827.966*3.00] mapped 74507 sequences
[M::worker_pipeline::1030.804*3.01] mapped 74619 sequences
[M::worker_pipeline::1229.208*3.02] mapped 74121 sequences
[M::worker_pipeline::1425.155*3.03] mapped 73264 sequences
[M::worker_pipeline::1628.688*3.03] mapped 73582 sequences
[M::worker_pipeline::1830.148*3.03] mapped 73648 sequences
[M::worker_pipeline::2031.096*3.04] mapped 79285 sequences
[M::worker_pipeline::2229.023*3.04] mapped 72784 sequences
[M::worker_pipeline::2426.087*3.04] mapped 76179 sequences
[M::worker_pipeline::2621.985*3.04] mapped 72666 sequences
[M::worker_pipeline::2821.545*3.04] mapped 72943 sequences
[M::worker_pipeline::3020.565*3.04] mapped 76320 sequences
[M::worker_pipeline::3217.225*3.05] mapped 74679 sequences
[M::worker_pipeline::3413.863*3.05] mapped 72162 sequences
[M::worker_pipeline::3612.976*3.05] mapped 72310 sequences
[M::worker_pipeline::3815.636*3.05] mapped 71973 sequences
[M::worker_pipeline::4008.823*3.05] mapped 71669 sequences
[M::worker_pipeline::4205.279*3.05] mapped 76851 sequences
[M::worker_pipeline::4405.507*3.05] mapped 72077 sequences
[M::worker_pipeline::4600.431*3.05] mapped 71886 sequences
[M::worker_pipeline::4799.354*3.05] mapped 71793 sequences
[M::worker_pipeline::4995.093*3.05] mapped 71416 sequences
[M::worker_pipeline::5188.572*3.05] mapped 75720 sequences
[M::worker_pipeline::5388.207*3.05] mapped 71804 sequences
[M::worker_pipeline::5590.525*3.05] mapped 71150 sequences
[M::worker_pipeline::5793.017*3.05] mapped 71555 sequences
[M::worker_pipeline::5992.453*3.05] mapped 74876 sequences
[M::worker_pipeline::6191.767*3.05] mapped 71128 sequences
[M::worker_pipeline::6396.589*3.05] mapped 71460 sequences
[M::worker_pipeline::6596.435*3.05] mapped 71393 sequences
[M::worker_pipeline::6798.326*3.05] mapped 74164 sequences
[M::worker_pipeline::7004.542*3.05] mapped 71135 sequences
[M::worker_pipeline::7203.476*3.05] mapped 70674 sequences
[M::worker_pipeline::7403.270*3.06] mapped 74515 sequences
[M::worker_pipeline::7602.832*3.06] mapped 71245 sequences
[M::worker_pipeline::7802.639*3.06] mapped 71251 sequences
[M::worker_pipeline::8008.924*3.06] mapped 74401 sequences
[M::worker_pipeline::8209.043*3.06] mapped 71098 sequences
[M::worker_pipeline::8417.129*3.06] mapped 73657 sequences
[M::worker_pipeline::8629.010*3.06] mapped 71178 sequences
[M::worker_pipeline::8838.043*3.06] mapped 71772 sequences
[M::worker_pipeline::9035.898*3.06] mapped 73791 sequences
[M::worker_pipeline::9238.100*3.06] mapped 73558 sequences
[M::worker_pipeline::9435.856*3.06] mapped 69950 sequences
[M::worker_pipeline::9638.776*3.06] mapped 70588 sequences
[M::worker_pipeline::9839.687*3.06] mapped 73993 sequences
[M::worker_pipeline::10034.580*3.06] mapped 72015 sequences
[M::worker_pipeline::10231.116*3.06] mapped 73594 sequences
[M::worker_pipeline::10423.418*3.06] mapped 72022 sequences
[M::worker_pipeline::10615.037*3.06] mapped 73997 sequences
[M::worker_pipeline::10810.581*3.06] mapped 73364 sequences
[M::worker_pipeline::11004.767*3.06] mapped 72582 sequences
[M::worker_pipeline::11201.915*3.06] mapped 75792 sequences
[M::worker_pipeline::11392.220*3.06] mapped 75339 sequences
[M::worker_pipeline::11578.960*3.06] mapped 75014 sequences
[M::worker_pipeline::11779.176*3.06] mapped 75319 sequences
[M::worker_pipeline::11978.762*3.06] mapped 76767 sequences
[M::worker_pipeline::12178.886*3.06] mapped 78693 sequences
[M::worker_pipeline::12387.326*3.06] mapped 85480 sequences
[M::worker_pipeline::12598.896*3.06] mapped 74610 sequences
[M::worker_pipeline::12819.690*3.06] mapped 75393 sequences
[M::worker_pipeline::13029.600*3.06] mapped 74927 sequences
[M::worker_pipeline::13222.778*3.06] mapped 69026 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -a out/minimap/Canis_familiaris.mmi data/raw_data/nanopore/D-85-01.fastq.gz
[M::main] Real time: 13223.662 sec; CPU: 40445.688 sec; Peak RSS: 10.867 GB
[E::bam_write1] Positional data is too large for BAM format
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
