PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/inv_50_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.anno.filtered.curated.inv.50.vcf

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 144 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/inv_50_plinkfile-temporary.pgen +
data/plink/inv_50_plinkfile-temporary.pvar.zst +
data/plink/inv_50_plinkfile-temporary.psam written.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/inv_50_plinkfile-temporary.psam.
144 variants loaded from data/plink/inv_50_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/inv_50_plinkfile.pvar ... 0%done.
Writing data/plink/inv_50_plinkfile.psam ... done.
Writing data/plink/inv_50_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:30 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/inv_50_pca
  --pca 10
  --pfile data/plink/inv_50_plinkfile
  --threads 4

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/inv_50_plinkfile.psam.
144 variants loaded from data/plink/inv_50_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/inv_50_pca.eigenvec , and eigenvalues
written to data/plink/inv_50_pca.eigenval .
End time: Tue May 23 13:30:30 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_subset_se_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/inv_50_subset_se_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.inv.50.subset_se.vcf

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 144 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/inv_50_subset_se_plinkfile-temporary.pgen +
data/plink/inv_50_subset_se_plinkfile-temporary.pvar.zst +
data/plink/inv_50_subset_se_plinkfile-temporary.psam written.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/inv_50_subset_se_plinkfile-temporary.psam.
144 variants loaded from
data/plink/inv_50_subset_se_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/inv_50_subset_se_plinkfile.pvar ... 0%done.
Writing data/plink/inv_50_subset_se_plinkfile.psam ... done.
Writing data/plink/inv_50_subset_se_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:30 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_subset_se_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/inv_50_subset_se_pca
  --pca 10
  --pfile data/plink/inv_50_subset_se_plinkfile
  --threads 4

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/inv_50_subset_se_plinkfile.psam.
144 variants loaded from data/plink/inv_50_subset_se_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/inv_50_subset_se_pca.eigenvec , and
eigenvalues written to data/plink/inv_50_subset_se_pca.eigenval .
End time: Tue May 23 13:30:30 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_subset_fi_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/inv_50_subset_fi_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.inv.50.subset_fi.vcf

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 144 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/inv_50_subset_fi_plinkfile-temporary.pgen +
data/plink/inv_50_subset_fi_plinkfile-temporary.pvar.zst +
data/plink/inv_50_subset_fi_plinkfile-temporary.psam written.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/inv_50_subset_fi_plinkfile-temporary.psam.
144 variants loaded from
data/plink/inv_50_subset_fi_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/inv_50_subset_fi_plinkfile.pvar ... 0%done.
Writing data/plink/inv_50_subset_fi_plinkfile.psam ... done.
Writing data/plink/inv_50_subset_fi_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:30 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/inv_50_subset_fi_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/inv_50_subset_fi_pca
  --pca 10
  --pfile data/plink/inv_50_subset_fi_plinkfile
  --threads 4

Start time: Tue May 23 13:30:30 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/inv_50_subset_fi_plinkfile.psam.
144 variants loaded from data/plink/inv_50_subset_fi_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/inv_50_subset_fi_pca.eigenvec , and
eigenvalues written to data/plink/inv_50_subset_fi_pca.eigenval .
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/dup_50_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.anno.filtered.curated.dup.50.vcf

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 1040 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/dup_50_plinkfile-temporary.pgen +
data/plink/dup_50_plinkfile-temporary.pvar.zst +
data/plink/dup_50_plinkfile-temporary.psam written.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/dup_50_plinkfile-temporary.psam.
1040 variants loaded from data/plink/dup_50_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/dup_50_plinkfile.pvar ... 0%done.
Writing data/plink/dup_50_plinkfile.psam ... done.
Writing data/plink/dup_50_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/dup_50_pca
  --pca 10
  --pfile data/plink/dup_50_plinkfile
  --threads 4

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/dup_50_plinkfile.psam.
1040 variants loaded from data/plink/dup_50_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%13%27%41%55%69%83%96%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/dup_50_pca.eigenvec , and eigenvalues
written to data/plink/dup_50_pca.eigenval .
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_subset_se_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/dup_50_subset_se_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.dup.50.subset_se.vcf

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 1040 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/dup_50_subset_se_plinkfile-temporary.pgen +
data/plink/dup_50_subset_se_plinkfile-temporary.pvar.zst +
data/plink/dup_50_subset_se_plinkfile-temporary.psam written.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/dup_50_subset_se_plinkfile-temporary.psam.
1040 variants loaded from
data/plink/dup_50_subset_se_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/dup_50_subset_se_plinkfile.pvar ... 0%done.
Writing data/plink/dup_50_subset_se_plinkfile.psam ... done.
Writing data/plink/dup_50_subset_se_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_subset_se_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/dup_50_subset_se_pca
  --pca 10
  --pfile data/plink/dup_50_subset_se_plinkfile
  --threads 4

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/dup_50_subset_se_plinkfile.psam.
1040 variants loaded from data/plink/dup_50_subset_se_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%13%27%41%55%69%83%96%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/dup_50_subset_se_pca.eigenvec , and
eigenvalues written to data/plink/dup_50_subset_se_pca.eigenval .
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_subset_fi_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/dup_50_subset_fi_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.dup.50.subset_fi.vcf

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 1040 variants scanned.
--vcf: 0k variants converted.    --vcf: data/plink/dup_50_subset_fi_plinkfile-temporary.pgen +
data/plink/dup_50_subset_fi_plinkfile-temporary.pvar.zst +
data/plink/dup_50_subset_fi_plinkfile-temporary.psam written.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/dup_50_subset_fi_plinkfile-temporary.psam.
1040 variants loaded from
data/plink/dup_50_subset_fi_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/dup_50_subset_fi_plinkfile.pvar ... 0%done.
Writing data/plink/dup_50_subset_fi_plinkfile.psam ... done.
Writing data/plink/dup_50_subset_fi_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/dup_50_subset_fi_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/dup_50_subset_fi_pca
  --pca 10
  --pfile data/plink/dup_50_subset_fi_plinkfile
  --threads 4

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/dup_50_subset_fi_plinkfile.psam.
1040 variants loaded from data/plink/dup_50_subset_fi_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%13%27%41%55%69%83%96%done.
Correcting for missingness... 0%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/dup_50_subset_fi_pca.eigenvec , and
eigenvalues written to data/plink/dup_50_subset_fi_pca.eigenval .
End time: Tue May 23 13:30:31 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/del_50_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.anno.filtered.curated.del.50.vcf

Start time: Tue May 23 13:30:31 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 2k variants scanned.--vcf: 3k variants scanned.--vcf: 4k variants scanned.--vcf: 5k variants scanned.--vcf: 6k variants scanned.--vcf: 7k variants scanned.--vcf: 8k variants scanned.--vcf: 9k variants scanned.--vcf: 10k variants scanned.--vcf: 11k variants scanned.--vcf: 12k variants scanned.--vcf: 13k variants scanned.--vcf: 14k variants scanned.--vcf: 15k variants scanned.--vcf: 16k variants scanned.--vcf: 17k variants scanned.--vcf: 18k variants scanned.--vcf: 19k variants scanned.--vcf: 20k variants scanned.--vcf: 21k variants scanned.--vcf: 22k variants scanned.--vcf: 23k variants scanned.--vcf: 24k variants scanned.--vcf: 25k variants scanned.--vcf: 26k variants scanned.--vcf: 27k variants scanned.--vcf: 28k variants scanned.--vcf: 29k variants scanned.--vcf: 30k variants scanned.--vcf: 30616 variants scanned.
--vcf: 15k variants converted.    --vcf: data/plink/del_50_plinkfile-temporary.pgen +
data/plink/del_50_plinkfile-temporary.pvar.zst +
data/plink/del_50_plinkfile-temporary.psam written.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/del_50_plinkfile-temporary.psam.
30616 variants loaded from data/plink/del_50_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/del_50_plinkfile.pvar ... 0%done.
Writing data/plink/del_50_plinkfile.psam ... done.
Writing data/plink/del_50_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:33 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/del_50_pca
  --pca 10
  --pfile data/plink/del_50_plinkfile
  --threads 4

Start time: Tue May 23 13:30:33 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
212 samples (0 females, 0 males, 212 ambiguous; 212 founders) loaded from
data/plink/del_50_plinkfile.psam.
30616 variants loaded from data/plink/del_50_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99%done.
Correcting for missingness... 0%4%9%14%19%24%29%34%39%44%49%53%58%63%68%73%78%83%88%93%98%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/del_50_pca.eigenvec , and eigenvalues
written to data/plink/del_50_pca.eigenval .
End time: Tue May 23 13:30:33 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_subset_se_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/del_50_subset_se_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.del.50.subset_se.vcf

Start time: Tue May 23 13:30:33 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 2k variants scanned.--vcf: 3k variants scanned.--vcf: 4k variants scanned.--vcf: 5k variants scanned.--vcf: 6k variants scanned.--vcf: 7k variants scanned.--vcf: 8k variants scanned.--vcf: 9k variants scanned.--vcf: 10k variants scanned.--vcf: 11k variants scanned.--vcf: 12k variants scanned.--vcf: 13k variants scanned.--vcf: 14k variants scanned.--vcf: 15k variants scanned.--vcf: 16k variants scanned.--vcf: 17k variants scanned.--vcf: 18k variants scanned.--vcf: 19k variants scanned.--vcf: 20k variants scanned.--vcf: 21k variants scanned.--vcf: 22k variants scanned.--vcf: 23k variants scanned.--vcf: 24k variants scanned.--vcf: 25k variants scanned.--vcf: 26k variants scanned.--vcf: 27k variants scanned.--vcf: 28k variants scanned.--vcf: 29k variants scanned.--vcf: 30k variants scanned.--vcf: 30616 variants scanned.
--vcf: 15k variants converted.    --vcf: data/plink/del_50_subset_se_plinkfile-temporary.pgen +
data/plink/del_50_subset_se_plinkfile-temporary.pvar.zst +
data/plink/del_50_subset_se_plinkfile-temporary.psam written.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/del_50_subset_se_plinkfile-temporary.psam.
30616 variants loaded from
data/plink/del_50_subset_se_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/del_50_subset_se_plinkfile.pvar ... 0%done.
Writing data/plink/del_50_subset_se_plinkfile.psam ... done.
Writing data/plink/del_50_subset_se_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:35 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_subset_se_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/del_50_subset_se_pca
  --pca 10
  --pfile data/plink/del_50_subset_se_plinkfile
  --threads 4

Start time: Tue May 23 13:30:35 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
97 samples (0 females, 0 males, 97 ambiguous; 97 founders) loaded from
data/plink/del_50_subset_se_plinkfile.psam.
30616 variants loaded from data/plink/del_50_subset_se_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99%done.
Correcting for missingness... 0%6%12%18%24%30%36%42%48%54%60%67%73%79%85%91%97%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/del_50_subset_se_pca.eigenvec , and
eigenvalues written to data/plink/del_50_subset_se_pca.eigenval .
End time: Tue May 23 13:30:35 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_subset_fi_plinkfile.log.
Options in effect:
  --autosome-num 38
  --make-pgen
  --out data/plink/del_50_subset_fi_plinkfile
  --sort-vars
  --vcf data/plotcritic/cohort.curated.del.50.subset_fi.vcf

Start time: Tue May 23 13:30:35 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
--vcf: 1k variants scanned.--vcf: 2k variants scanned.--vcf: 3k variants scanned.--vcf: 4k variants scanned.--vcf: 5k variants scanned.--vcf: 6k variants scanned.--vcf: 7k variants scanned.--vcf: 8k variants scanned.--vcf: 9k variants scanned.--vcf: 10k variants scanned.--vcf: 11k variants scanned.--vcf: 12k variants scanned.--vcf: 13k variants scanned.--vcf: 14k variants scanned.--vcf: 15k variants scanned.--vcf: 16k variants scanned.--vcf: 17k variants scanned.--vcf: 18k variants scanned.--vcf: 19k variants scanned.--vcf: 20k variants scanned.--vcf: 21k variants scanned.--vcf: 22k variants scanned.--vcf: 23k variants scanned.--vcf: 24k variants scanned.--vcf: 25k variants scanned.--vcf: 26k variants scanned.--vcf: 27k variants scanned.--vcf: 28k variants scanned.--vcf: 29k variants scanned.--vcf: 30k variants scanned.--vcf: 30616 variants scanned.
--vcf: 15k variants converted.    --vcf: data/plink/del_50_subset_fi_plinkfile-temporary.pgen +
data/plink/del_50_subset_fi_plinkfile-temporary.pvar.zst +
data/plink/del_50_subset_fi_plinkfile-temporary.psam written.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/del_50_subset_fi_plinkfile-temporary.psam.
30616 variants loaded from
data/plink/del_50_subset_fi_plinkfile-temporary.pvar.zst.
Note: No phenotype data present.
Writing data/plink/del_50_subset_fi_plinkfile.pvar ... 0%done.
Writing data/plink/del_50_subset_fi_plinkfile.psam ... done.
Writing data/plink/del_50_subset_fi_plinkfile.pgen ... 0%done.
End time: Tue May 23 13:30:37 2023
PLINK v2.00a3.7LM AVX2 Intel (24 Oct 2022)     www.cog-genomics.org/plink/2.0/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to data/plink/del_50_subset_fi_pca.log.
Options in effect:
  --autosome-num 38
  --out data/plink/del_50_subset_fi_pca
  --pca 10
  --pfile data/plink/del_50_subset_fi_plinkfile
  --threads 4

Start time: Tue May 23 13:30:37 2023
128373 MiB RAM detected; reserving 64186 MiB for main workspace.
Using up to 4 compute threads.
101 samples (0 females, 0 males, 101 ambiguous; 101 founders) loaded from
data/plink/del_50_subset_fi_plinkfile.psam.
30616 variants loaded from data/plink/del_50_subset_fi_plinkfile.pvar.
Note: No phenotype data present.
Calculating allele frequencies... 0%done.
Constructing GRM: 0%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30%31%32%33%34%35%36%37%38%39%40%41%42%43%44%45%46%47%48%49%50%51%52%53%54%55%56%57%58%59%60%61%62%63%64%65%66%67%68%69%70%71%72%73%74%75%76%77%78%79%80%81%82%83%84%85%86%87%88%89%90%91%92%93%94%95%96%97%98%99%done.
Correcting for missingness... 0%11%23%34%46%58%69%81%93%done.
Extracting eigenvalues and eigenvectors... done.
--pca: Eigenvectors written to data/plink/del_50_subset_fi_pca.eigenvec , and
eigenvalues written to data/plink/del_50_subset_fi_pca.eigenval .
End time: Tue May 23 13:30:37 2023
