Estimating parameter...
	Max dist between aln events: 7
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: 0.0421841
	Avg INS ratio: 0.0381503
Start parsing... 1
		# Processed reads: 10000
		# Processed reads: 20000
		# Processed reads: 30000
		# Processed reads: 40000
		# Processed reads: 50000
		# Processed reads: 60000
		# Processed reads: 70000
		# Processed reads: 80000
		# Processed reads: 90000
		# Processed reads: 100000
		# Processed reads: 110000
		# Processed reads: 120000
		# Processed reads: 130000
		# Processed reads: 140000
		# Processed reads: 150000
		# Processed reads: 160000
		# Processed reads: 170000
		# Processed reads: 180000
		# Processed reads: 190000
		# Processed reads: 200000
		# Processed reads: 210000
		# Processed reads: 220000
		# Processed reads: 230000
		# Processed reads: 240000
		# Processed reads: 250000
	Switch Chr 10
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 260000
		# Processed reads: 270000
		# Processed reads: 280000
		# Processed reads: 290000
		# Processed reads: 300000
		# Processed reads: 310000
		# Processed reads: 320000
		# Processed reads: 330000
		# Processed reads: 340000
		# Processed reads: 350000
		# Processed reads: 360000
		# Processed reads: 370000
		# Processed reads: 380000
		# Processed reads: 390000
	Switch Chr 11
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 400000
		# Processed reads: 410000
		# Processed reads: 420000
		# Processed reads: 430000
		# Processed reads: 440000
		# Processed reads: 450000
		# Processed reads: 460000
		# Processed reads: 470000
		# Processed reads: 480000
		# Processed reads: 490000
		# Processed reads: 500000
		# Processed reads: 510000
		# Processed reads: 520000
		# Processed reads: 530000
		# Processed reads: 540000
	Switch Chr 12
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 550000
		# Processed reads: 560000
		# Processed reads: 570000
		# Processed reads: 580000
		# Processed reads: 590000
		# Processed reads: 600000
		# Processed reads: 610000
		# Processed reads: 620000
		# Processed reads: 630000
		# Processed reads: 640000
		# Processed reads: 650000
		# Processed reads: 660000
		# Processed reads: 670000
		# Processed reads: 680000
		# Processed reads: 690000
	Switch Chr 13
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 700000
		# Processed reads: 710000
		# Processed reads: 720000
		# Processed reads: 730000
		# Processed reads: 740000
		# Processed reads: 750000
		# Processed reads: 760000
		# Processed reads: 770000
		# Processed reads: 780000
		# Processed reads: 790000
		# Processed reads: 800000
		# Processed reads: 810000
		# Processed reads: 820000
	Switch Chr 14
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 830000
		# Processed reads: 840000
		# Processed reads: 850000
		# Processed reads: 860000
		# Processed reads: 870000
		# Processed reads: 880000
		# Processed reads: 890000
		# Processed reads: 900000
		# Processed reads: 910000
		# Processed reads: 920000
		# Processed reads: 930000
		# Processed reads: 940000
		# Processed reads: 950000
	Switch Chr 15
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 960000
		# Processed reads: 970000
		# Processed reads: 980000
		# Processed reads: 990000
		# Processed reads: 1000000
		# Processed reads: 1010000
		# Processed reads: 1020000
		# Processed reads: 1030000
		# Processed reads: 1040000
		# Processed reads: 1050000
		# Processed reads: 1060000
		# Processed reads: 1070000
		# Processed reads: 1080000
	Switch Chr 16
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1090000
		# Processed reads: 1100000
		# Processed reads: 1110000
		# Processed reads: 1120000
		# Processed reads: 1130000
		# Processed reads: 1140000
		# Processed reads: 1150000
		# Processed reads: 1160000
		# Processed reads: 1170000
		# Processed reads: 1180000
		# Processed reads: 1190000
		# Processed reads: 1200000
	Switch Chr 17
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1210000
		# Processed reads: 1220000
		# Processed reads: 1230000
		# Processed reads: 1240000
		# Processed reads: 1250000
		# Processed reads: 1260000
		# Processed reads: 1270000
		# Processed reads: 1280000
		# Processed reads: 1290000
		# Processed reads: 1300000
		# Processed reads: 1310000
		# Processed reads: 1320000
		# Processed reads: 1330000
	Switch Chr 18
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1340000
		# Processed reads: 1350000
		# Processed reads: 1360000
		# Processed reads: 1370000
		# Processed reads: 1380000
		# Processed reads: 1390000
		# Processed reads: 1400000
		# Processed reads: 1410000
		# Processed reads: 1420000
		# Processed reads: 1430000
		# Processed reads: 1440000
		# Processed reads: 1450000
	Switch Chr 19
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1460000
		# Processed reads: 1470000
		# Processed reads: 1480000
		# Processed reads: 1490000
		# Processed reads: 1500000
		# Processed reads: 1510000
		# Processed reads: 1520000
		# Processed reads: 1530000
		# Processed reads: 1540000
		# Processed reads: 1550000
		# Processed reads: 1560000
	Switch Chr 2
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1570000
		# Processed reads: 1580000
		# Processed reads: 1590000
		# Processed reads: 1600000
		# Processed reads: 1610000
		# Processed reads: 1620000
		# Processed reads: 1630000
		# Processed reads: 1640000
		# Processed reads: 1650000
		# Processed reads: 1660000
		# Processed reads: 1670000
		# Processed reads: 1680000
		# Processed reads: 1690000
		# Processed reads: 1700000
		# Processed reads: 1710000
		# Processed reads: 1720000
		# Processed reads: 1730000
		# Processed reads: 1740000
	Switch Chr 20
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1750000
		# Processed reads: 1760000
		# Processed reads: 1770000
		# Processed reads: 1780000
		# Processed reads: 1790000
		# Processed reads: 1800000
		# Processed reads: 1810000
		# Processed reads: 1820000
		# Processed reads: 1830000
		# Processed reads: 1840000
		# Processed reads: 1850000
		# Processed reads: 1860000
	Switch Chr 21
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1870000
		# Processed reads: 1880000
		# Processed reads: 1890000
		# Processed reads: 1900000
		# Processed reads: 1910000
		# Processed reads: 1920000
		# Processed reads: 1930000
		# Processed reads: 1940000
		# Processed reads: 1950000
		# Processed reads: 1960000
	Switch Chr 22
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 1970000
		# Processed reads: 1980000
		# Processed reads: 1990000
		# Processed reads: 2000000
		# Processed reads: 2010000
		# Processed reads: 2020000
		# Processed reads: 2030000
		# Processed reads: 2040000
		# Processed reads: 2050000
		# Processed reads: 2060000
		# Processed reads: 2070000
		# Processed reads: 2080000
		# Processed reads: 2090000
	Switch Chr 23
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2100000
		# Processed reads: 2110000
		# Processed reads: 2120000
		# Processed reads: 2130000
		# Processed reads: 2140000
		# Processed reads: 2150000
		# Processed reads: 2160000
		# Processed reads: 2170000
		# Processed reads: 2180000
		# Processed reads: 2190000
		# Processed reads: 2200000
	Switch Chr 24
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2210000
		# Processed reads: 2220000
		# Processed reads: 2230000
		# Processed reads: 2240000
		# Processed reads: 2250000
		# Processed reads: 2260000
		# Processed reads: 2270000
		# Processed reads: 2280000
		# Processed reads: 2290000
	Switch Chr 25
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2300000
		# Processed reads: 2310000
		# Processed reads: 2320000
		# Processed reads: 2330000
		# Processed reads: 2340000
		# Processed reads: 2350000
		# Processed reads: 2360000
		# Processed reads: 2370000
		# Processed reads: 2380000
		# Processed reads: 2390000
		# Processed reads: 2400000
	Switch Chr 26
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2410000
		# Processed reads: 2420000
		# Processed reads: 2430000
		# Processed reads: 2440000
		# Processed reads: 2450000
		# Processed reads: 2460000
		# Processed reads: 2470000
		# Processed reads: 2480000
	Switch Chr 27
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2490000
		# Processed reads: 2500000
		# Processed reads: 2510000
		# Processed reads: 2520000
		# Processed reads: 2530000
		# Processed reads: 2540000
		# Processed reads: 2550000
		# Processed reads: 2560000
		# Processed reads: 2570000
	Switch Chr 28
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2580000
		# Processed reads: 2590000
		# Processed reads: 2600000
		# Processed reads: 2610000
		# Processed reads: 2620000
		# Processed reads: 2630000
		# Processed reads: 2640000
		# Processed reads: 2650000
		# Processed reads: 2660000
	Switch Chr 29
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2670000
		# Processed reads: 2680000
		# Processed reads: 2690000
		# Processed reads: 2700000
		# Processed reads: 2710000
		# Processed reads: 2720000
		# Processed reads: 2730000
		# Processed reads: 2740000
	Switch Chr 3
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2750000
		# Processed reads: 2760000
		# Processed reads: 2770000
		# Processed reads: 2780000
		# Processed reads: 2790000
		# Processed reads: 2800000
		# Processed reads: 2810000
		# Processed reads: 2820000
		# Processed reads: 2830000
		# Processed reads: 2840000
		# Processed reads: 2850000
		# Processed reads: 2860000
		# Processed reads: 2870000
		# Processed reads: 2880000
		# Processed reads: 2890000
		# Processed reads: 2900000
		# Processed reads: 2910000
		# Processed reads: 2920000
		# Processed reads: 2930000
	Switch Chr 30
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 2940000
		# Processed reads: 2950000
		# Processed reads: 2960000
		# Processed reads: 2970000
		# Processed reads: 2980000
		# Processed reads: 2990000
		# Processed reads: 3000000
		# Processed reads: 3010000
		# Processed reads: 3020000
	Switch Chr 31
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3030000
		# Processed reads: 3040000
		# Processed reads: 3050000
		# Processed reads: 3060000
		# Processed reads: 3070000
		# Processed reads: 3080000
		# Processed reads: 3090000
	Switch Chr 32
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3100000
		# Processed reads: 3110000
		# Processed reads: 3120000
		# Processed reads: 3130000
		# Processed reads: 3140000
		# Processed reads: 3150000
		# Processed reads: 3160000
		# Processed reads: 3170000
	Switch Chr 33
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3180000
		# Processed reads: 3190000
		# Processed reads: 3200000
		# Processed reads: 3210000
		# Processed reads: 3220000
		# Processed reads: 3230000
		# Processed reads: 3240000
	Switch Chr 34
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3250000
		# Processed reads: 3260000
		# Processed reads: 3270000
		# Processed reads: 3280000
		# Processed reads: 3290000
		# Processed reads: 3300000
		# Processed reads: 3310000
		# Processed reads: 3320000
		# Processed reads: 3330000
	Switch Chr 35
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3340000
		# Processed reads: 3350000
		# Processed reads: 3360000
		# Processed reads: 3370000
		# Processed reads: 3380000
	Switch Chr 36
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3390000
		# Processed reads: 3400000
		# Processed reads: 3410000
		# Processed reads: 3420000
		# Processed reads: 3430000
		# Processed reads: 3440000
		# Processed reads: 3450000
	Switch Chr 37
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3460000
		# Processed reads: 3470000
		# Processed reads: 3480000
		# Processed reads: 3490000
		# Processed reads: 3500000
		# Processed reads: 3510000
	Switch Chr 38
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3520000
		# Processed reads: 3530000
		# Processed reads: 3540000
		# Processed reads: 3550000
		# Processed reads: 3560000
	Switch Chr 4
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3570000
		# Processed reads: 3580000
		# Processed reads: 3590000
		# Processed reads: 3600000
		# Processed reads: 3610000
		# Processed reads: 3620000
		# Processed reads: 3630000
		# Processed reads: 3640000
		# Processed reads: 3650000
		# Processed reads: 3660000
		# Processed reads: 3670000
		# Processed reads: 3680000
		# Processed reads: 3690000
		# Processed reads: 3700000
		# Processed reads: 3710000
		# Processed reads: 3720000
		# Processed reads: 3730000
		# Processed reads: 3740000
	Switch Chr 5
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3750000
		# Processed reads: 3760000
		# Processed reads: 3770000
		# Processed reads: 3780000
		# Processed reads: 3790000
		# Processed reads: 3800000
		# Processed reads: 3810000
		# Processed reads: 3820000
		# Processed reads: 3830000
		# Processed reads: 3840000
		# Processed reads: 3850000
		# Processed reads: 3860000
		# Processed reads: 3870000
		# Processed reads: 3880000
		# Processed reads: 3890000
		# Processed reads: 3900000
		# Processed reads: 3910000
		# Processed reads: 3920000
	Switch Chr 6
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 3930000
		# Processed reads: 3940000
		# Processed reads: 3950000
		# Processed reads: 3960000
		# Processed reads: 3970000
		# Processed reads: 3980000
		# Processed reads: 3990000
		# Processed reads: 4000000
		# Processed reads: 4010000
		# Processed reads: 4020000
		# Processed reads: 4030000
		# Processed reads: 4040000
		# Processed reads: 4050000
		# Processed reads: 4060000
		# Processed reads: 4070000
		# Processed reads: 4080000
	Switch Chr 7
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4090000
		# Processed reads: 4100000
		# Processed reads: 4110000
		# Processed reads: 4120000
		# Processed reads: 4130000
		# Processed reads: 4140000
		# Processed reads: 4150000
		# Processed reads: 4160000
		# Processed reads: 4170000
		# Processed reads: 4180000
		# Processed reads: 4190000
		# Processed reads: 4200000
		# Processed reads: 4210000
		# Processed reads: 4220000
		# Processed reads: 4230000
		# Processed reads: 4240000
		# Processed reads: 4250000
		# Processed reads: 4260000
	Switch Chr 8
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4270000
		# Processed reads: 4280000
		# Processed reads: 4290000
		# Processed reads: 4300000
		# Processed reads: 4310000
		# Processed reads: 4320000
		# Processed reads: 4330000
		# Processed reads: 4340000
		# Processed reads: 4350000
		# Processed reads: 4360000
		# Processed reads: 4370000
		# Processed reads: 4380000
		# Processed reads: 4390000
		# Processed reads: 4400000
		# Processed reads: 4410000
	Switch Chr 9
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4420000
		# Processed reads: 4430000
		# Processed reads: 4440000
		# Processed reads: 4450000
		# Processed reads: 4460000
		# Processed reads: 4470000
		# Processed reads: 4480000
		# Processed reads: 4490000
		# Processed reads: 4500000
		# Processed reads: 4510000
		# Processed reads: 4520000
		# Processed reads: 4530000
		# Processed reads: 4540000
	Switch Chr MT
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4550000
		# Processed reads: 4560000
		# Processed reads: 4570000
		# Processed reads: 4580000
		# Processed reads: 4590000
		# Processed reads: 4600000
	Switch Chr X
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4610000
		# Processed reads: 4620000
		# Processed reads: 4630000
		# Processed reads: 4640000
		# Processed reads: 4650000
		# Processed reads: 4660000
		# Processed reads: 4670000
		# Processed reads: 4680000
		# Processed reads: 4690000
		# Processed reads: 4700000
		# Processed reads: 4710000
		# Processed reads: 4720000
		# Processed reads: 4730000
		# Processed reads: 4740000
		# Processed reads: 4750000
		# Processed reads: 4760000
		# Processed reads: 4770000
		# Processed reads: 4780000
		# Processed reads: 4790000
		# Processed reads: 4800000
		# Processed reads: 4810000
		# Processed reads: 4820000
		# Processed reads: 4830000
		# Processed reads: 4840000
	Switch Chr JH373233.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373234.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4850000
	Switch Chr JH373235.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373236.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373238.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4860000
	Switch Chr JH373237.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373239.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373241.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373240.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373244.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373242.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373249.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373243.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373250.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4870000
	Switch Chr JH373245.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373253.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373246.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373252.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373247.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373248.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373254.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373265.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373260.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373251.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4880000
	Switch Chr AAEX03018827.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373258.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373278.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373256.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373255.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373259.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373257.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373261.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373262.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373263.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373268.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373281.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373264.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373284.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373267.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4890000
	Switch Chr JH373266.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373269.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373336.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373273.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373272.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373270.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373271.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373335.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373371.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373276.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373274.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373275.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373277.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373280.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019065.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373290.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373286.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373279.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019090.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373283.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373282.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019097.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373287.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373288.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4900000
	Switch Chr JH373285.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373289.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373291.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373292.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373293.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373294.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373295.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373306.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373296.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373299.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373298.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373297.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019222.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019231.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373304.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373300.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373303.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019240.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373315.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373302.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373301.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019241.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373319.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373307.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373305.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373316.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373308.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373310.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019307.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373313.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373309.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373311.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373330.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373318.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373312.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019339.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019340.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373350.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019341.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373314.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373324.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373332.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373321.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373317.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373320.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373344.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4910000
	Switch Chr JH373348.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373322.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373327.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373325.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373323.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373367.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373326.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373376.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373443.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373341.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373394.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373343.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373380.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373366.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019443.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373334.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373328.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373329.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373362.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373432.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373355.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373389.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019490.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373342.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019491.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373331.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373333.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373337.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019492.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373356.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019535.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373345.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373346.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373354.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373340.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373351.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019548.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019560.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373339.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373338.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373414.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373412.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373347.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373353.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373419.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373349.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373352.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373383.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373382.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373427.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373368.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373421.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373446.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373396.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373370.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373477.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373387.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373357.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373409.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019681.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373503.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373451.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019691.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373358.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373400.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373365.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373494.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373422.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373359.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373385.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019738.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373360.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373364.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019763.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373363.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373467.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373369.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373372.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373424.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373480.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373476.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373407.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373378.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373386.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373374.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373373.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373375.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373377.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373379.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373442.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019872.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373384.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019893.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373408.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373505.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373393.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373425.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373390.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373474.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373445.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373388.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373398.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373411.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373420.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373540.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373450.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373452.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373397.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373481.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373438.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373401.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373395.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373439.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03019987.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373527.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373549.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373418.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373745.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373405.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373512.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373399.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373496.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373524.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373416.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373402.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020051.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373417.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373475.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373403.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020054.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373517.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373433.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020055.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020056.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373501.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373568.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373521.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373490.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373468.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373435.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4920000
	Switch Chr JH373404.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020060.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373588.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373479.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020068.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373622.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373410.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020105.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373415.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373413.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373434.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373423.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373430.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020161.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373465.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373566.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373548.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373461.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020170.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373558.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373457.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373614.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373464.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373426.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373444.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373526.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373460.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373429.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020242.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373488.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374024.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373472.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373695.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373463.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373431.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373440.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373604.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373441.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373478.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373437.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020335.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373449.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373454.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373447.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373453.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020381.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373703.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373519.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020403.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373448.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373513.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373623.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020427.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373580.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373507.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020436.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373471.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373613.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373542.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373487.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373455.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373456.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020482.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373576.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373459.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020487.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373575.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373466.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020497.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373644.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373489.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373469.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373529.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373731.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020524.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373528.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373643.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020533.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373807.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373626.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373486.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020568.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373572.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373569.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373732.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373840.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373541.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373571.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020574.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373624.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020588.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020610.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373484.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373573.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373504.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373485.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4930000
	Switch Chr JH373754.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373672.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373663.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373483.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373538.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373482.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373593.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373497.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020671.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373493.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373724.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373670.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020700.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020701.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373664.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373609.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373649.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373630.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373607.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373570.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373660.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373646.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373508.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020729.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373506.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373495.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373666.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373492.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373491.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373602.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373514.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020760.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020761.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373510.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373502.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373714.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373523.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373516.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020831.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373777.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373650.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373654.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020839.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373564.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020840.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373578.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373638.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373511.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373605.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373687.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373543.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373774.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373581.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373509.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373641.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373744.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373515.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373674.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373675.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020896.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373531.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373554.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020910.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373522.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373552.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020926.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373534.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373530.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373702.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373757.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020959.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020963.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373595.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373612.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373710.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020982.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373677.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373616.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03020983.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373956.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373533.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373683.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021041.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021042.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373597.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021043.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373539.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021044.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373553.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373653.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021070.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373787.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373562.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021071.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021077.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021094.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373642.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021108.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373550.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373547.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373723.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373600.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373647.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021139.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373555.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373565.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373606.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373563.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373557.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021187.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373559.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373617.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021193.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021208.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373619.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373561.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373601.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373639.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373830.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373721.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021227.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373793.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373692.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373746.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373567.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021268.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373699.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373598.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021281.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373694.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021282.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373585.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021317.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021318.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373658.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373582.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373713.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373817.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373579.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373685.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021345.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021372.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373704.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373583.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373784.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373584.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373785.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373753.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373608.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373586.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373591.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373635.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373603.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021408.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373596.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373592.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373802.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021437.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021458.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373686.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021463.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373655.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373640.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373853.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021489.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373893.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373712.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373727.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373689.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021540.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373615.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373719.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373618.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373876.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373859.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021579.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373706.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373759.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021599.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373738.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021648.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373632.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021649.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021660.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373716.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373631.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373735.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373867.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021682.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373892.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373656.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373707.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373637.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373781.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021701.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373636.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373990.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021719.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373760.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373798.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021736.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021737.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373749.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373671.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021761.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373832.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373878.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373797.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373743.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373682.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373668.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021790.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021800.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021807.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373887.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373775.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021822.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373690.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373809.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021841.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021842.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373691.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373963.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021849.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021853.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021854.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373659.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373829.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373679.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373873.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021919.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373705.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021932.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373856.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373676.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373684.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373820.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373858.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373904.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373863.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021979.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03021981.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373986.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373917.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373701.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022003.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022020.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373768.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022031.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373733.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022032.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373700.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022033.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373693.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022043.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022044.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373708.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022057.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373907.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022060.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373839.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373882.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022061.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022063.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373805.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373946.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022069.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373779.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373836.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022082.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022083.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373756.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373697.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373875.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022093.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373728.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373844.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373750.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022122.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022123.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373717.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373709.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022139.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373790.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022140.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022141.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373715.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373778.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022149.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373726.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022157.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022171.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373736.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373737.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022189.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022193.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373730.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022194.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022202.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4940000
	Switch Chr JH373886.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022203.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022204.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022211.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022212.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373993.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374006.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022216.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373825.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373764.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022223.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373964.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373925.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373722.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022239.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022240.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373826.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373765.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373752.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022242.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022243.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022244.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373811.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022256.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373932.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373739.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022277.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373981.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022291.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373751.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022299.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022301.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022317.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373914.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373841.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022329.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373755.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373741.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022332.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022348.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022357.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022359.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373748.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022378.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022381.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022384.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022390.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022391.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373846.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373795.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373850.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373772.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022441.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022448.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373818.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022474.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022475.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373770.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022476.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022477.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373783.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373822.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373771.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022496.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373888.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373810.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373801.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373794.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022555.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373843.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022578.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022579.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022582.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022592.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022606.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373930.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373861.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374017.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022651.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373900.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373824.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022659.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373982.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373934.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373889.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373937.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373935.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373814.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373819.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022692.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373816.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374004.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022706.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373815.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022707.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022712.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022713.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373821.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022735.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022738.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022739.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373898.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022740.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022741.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022742.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373879.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022744.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022754.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022755.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022756.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373849.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373939.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373950.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373978.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022760.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022761.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022764.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373928.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373915.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022777.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374038.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373949.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022785.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373975.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022786.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022787.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022788.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373884.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022814.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373880.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022820.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022821.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374053.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373972.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022848.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022849.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022858.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373911.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373842.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022862.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022863.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373890.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022877.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022878.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373954.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022890.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022907.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374065.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022909.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373872.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373857.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373874.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373869.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373967.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022915.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373916.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374104.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373973.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022944.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022945.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022980.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373885.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373948.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373966.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374027.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373918.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373983.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374001.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373868.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03022993.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373933.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023018.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023030.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373929.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374039.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023045.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023050.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023060.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373974.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373881.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373947.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023081.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023082.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374095.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023083.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023097.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373920.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373902.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374002.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023107.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023110.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373970.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373977.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374008.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374015.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373895.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373979.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374020.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374021.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373969.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023161.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023169.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023172.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374049.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373962.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374011.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373926.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023177.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373905.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023201.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373927.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374047.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023213.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373961.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374063.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023229.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373922.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023233.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023234.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023240.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374055.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023257.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023258.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373931.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374022.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023275.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023286.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023291.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374026.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373938.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023315.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023323.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373988.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373942.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374071.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374081.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373995.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374029.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023347.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374041.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023355.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023356.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023357.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023358.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023365.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023366.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023367.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373953.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023373.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023374.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023381.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023382.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023386.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373958.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374060.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373976.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374051.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023396.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374149.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374101.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374079.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023424.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374164.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023426.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023435.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH373984.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023449.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023450.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023452.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023460.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023468.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374163.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023484.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023493.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374074.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023504.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023507.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023508.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023514.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023518.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023519.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374019.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374117.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023521.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023522.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023524.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374091.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023536.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023537.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023538.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023556.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023558.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023559.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023563.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023573.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023576.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023586.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023594.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374109.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023617.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374166.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023627.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374106.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023640.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374013.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023651.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023664.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023665.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374007.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023686.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023691.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374122.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023696.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374136.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023702.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374012.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374130.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023725.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374058.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374077.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023732.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023735.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023736.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023737.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023742.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023744.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023755.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023760.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374146.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023762.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023767.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023770.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023772.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023779.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374086.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023784.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023786.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374032.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023809.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374124.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023812.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374111.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023823.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023824.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023825.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374172.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374054.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023828.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023830.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023832.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023837.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023840.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023848.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374059.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374107.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374151.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023881.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374087.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023883.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023884.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023885.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023887.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374042.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374152.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023901.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023913.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023920.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023923.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023924.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023928.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023929.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023933.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023935.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023940.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023951.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023968.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023980.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03023988.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374075.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374076.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024006.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024015.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024016.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374121.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024022.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374085.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024040.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024049.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024052.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374153.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024064.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374143.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024070.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024071.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374099.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374098.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024075.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024084.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024088.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024096.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024097.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024100.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024114.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024116.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024120.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024124.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024129.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024132.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374161.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024137.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374083.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024143.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024144.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024151.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024174.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024183.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024185.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024186.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374132.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024194.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374140.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024201.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024206.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024207.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374138.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024209.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374128.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374093.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024220.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374157.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024224.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024225.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024226.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024228.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024243.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374177.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024246.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024247.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024257.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024258.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024261.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024269.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024274.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024277.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024279.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024301.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024307.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024314.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024316.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024319.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024324.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024326.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024333.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024336.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024342.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024349.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024357.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024361.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024362.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024364.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024371.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024377.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024379.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024389.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024401.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024407.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024411.1
		Reassessing breakpoints
		Continue parsing
		# Processed reads: 4950000
	Switch Chr AAEX03024414.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024415.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374123.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024420.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024422.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024431.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024439.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024444.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024447.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024451.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024467.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024469.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024478.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024481.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024485.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024486.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024487.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024488.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374181.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024491.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024495.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024502.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374139.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024509.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024510.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024511.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024512.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024513.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024515.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024518.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024522.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024523.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024540.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024543.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024545.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024556.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024561.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024572.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024587.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024592.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024600.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024611.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024618.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024619.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024622.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374141.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024633.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024634.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024639.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024646.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024647.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024649.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024650.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024654.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024655.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024659.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024661.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374147.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024666.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024667.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024669.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024684.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374189.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024686.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024692.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024695.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024697.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024698.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024702.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024707.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024710.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024711.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024713.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024718.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024729.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024730.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024734.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024735.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024740.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024745.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024750.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024753.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024754.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024756.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024757.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024760.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024762.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024772.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024774.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024776.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024779.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024783.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024790.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024813.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024819.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024821.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024824.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024826.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024828.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024829.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024830.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024837.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024844.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024847.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024851.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024852.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024871.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374155.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024879.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024890.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024893.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024894.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024897.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024899.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374159.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024907.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024912.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024913.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024922.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024934.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024935.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024936.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024937.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024938.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374175.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024950.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024954.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024955.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374180.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024961.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024963.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024964.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024969.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024974.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024977.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024980.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024987.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024988.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024990.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03024996.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025000.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025005.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025013.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025016.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025018.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025020.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025031.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025036.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374165.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025041.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025048.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025054.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025059.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025060.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025061.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025063.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025064.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025065.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374169.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025066.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025082.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025085.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025087.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025092.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025097.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025098.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025101.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025102.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374191.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025121.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025125.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025132.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025136.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025140.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025141.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025142.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025144.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374174.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025149.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025151.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025155.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025157.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025158.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025160.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025165.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr JH374176.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025172.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025175.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025181.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025188.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025189.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025195.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025203.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025205.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025206.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025209.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025214.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025217.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025220.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025221.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025223.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025228.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025238.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025240.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025248.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025250.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025251.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025254.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025256.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025257.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025258.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025259.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025262.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025265.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025274.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025275.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025280.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025283.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025285.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025287.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025293.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025296.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025307.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025320.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025323.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025324.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025328.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025330.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025333.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025334.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025335.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025336.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025347.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025353.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025355.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025356.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025358.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025360.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025372.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025377.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025378.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025379.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025385.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025387.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025394.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025398.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025400.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025401.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025402.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025409.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025411.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025415.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025416.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025422.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025429.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025431.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025434.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025435.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025437.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025439.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025440.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025442.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025455.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025470.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025474.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025486.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025489.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025491.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025495.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025496.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025502.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025505.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025508.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025509.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025511.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025518.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025523.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025524.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025528.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025530.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025531.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025540.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025541.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025550.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025569.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025571.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025572.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025581.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025583.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025586.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025597.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025602.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025604.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025612.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025618.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025637.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025643.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025644.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025647.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025648.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025658.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025659.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025661.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025665.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025667.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025677.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025680.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025684.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025686.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025689.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025702.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025704.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025712.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025715.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025721.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025726.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025727.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025729.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025731.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025736.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025737.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025740.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025742.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025744.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025749.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025751.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025755.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025757.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025767.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025768.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025777.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025778.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025787.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025788.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025789.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025792.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025797.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025800.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025802.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025805.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025810.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025811.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025823.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025826.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025833.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025835.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025842.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025866.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025873.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025879.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025881.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025886.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025891.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025892.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025895.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025896.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025907.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025909.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025910.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025915.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025921.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025924.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025925.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025927.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025959.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025991.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03025992.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03026004.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03026011.1
		Reassessing breakpoints
		Continue parsing
	Switch Chr AAEX03026022.1
		Reassessing breakpoints
		Continue parsing
	Finalizing  ..
Start genotype calling:
		Read in SV: 5000
		Read in SV: 10000
		Read in SV: 15000
		Read in SV: 20000
		Read in SV: 25000
		Read in SV: 30000
		Read in SV: 35000
		Read in SV: 40000
	Reopening Bam file for parsing coverage 
		Switch Chr 10
		Switch Chr 11
		Switch Chr 12
		Switch Chr 13
		Switch Chr 14
		Switch Chr 15
		Switch Chr 16
		Switch Chr 17
		Switch Chr 18
		Switch Chr 19
		Switch Chr 2
		Switch Chr 20
		Switch Chr 21
		Switch Chr 22
		Switch Chr 23
		Switch Chr 24
		Switch Chr 25
		Switch Chr 26
		Switch Chr 27
		Switch Chr 28
		Switch Chr 29
		Switch Chr 3
		Switch Chr 30
		Switch Chr 31
		Switch Chr 32
		Switch Chr 33
		Switch Chr 34
		Switch Chr 35
		Switch Chr 36
		Switch Chr 37
		Switch Chr 38
		Switch Chr 4
		Switch Chr 5
		Switch Chr 6
		Switch Chr 7
		Switch Chr 8
		Switch Chr 9
		Switch Chr MT
		Switch Chr X
		Switch Chr JH373233.1
		Switch Chr JH373234.1
		Switch Chr JH373235.1
		Switch Chr JH373236.1
		Switch Chr JH373238.1
		Switch Chr JH373237.1
		Switch Chr JH373239.1
		Switch Chr JH373241.1
		Switch Chr JH373240.1
		Switch Chr JH373244.1
		Switch Chr JH373242.1
		Switch Chr JH373249.1
		Switch Chr JH373243.1
		Switch Chr JH373250.1
		Switch Chr JH373245.1
		Switch Chr JH373253.1
		Switch Chr JH373246.1
		Switch Chr JH373252.1
		Switch Chr JH373247.1
		Switch Chr JH373248.1
		Switch Chr JH373254.1
		Switch Chr JH373265.1
		Switch Chr JH373260.1
		Switch Chr JH373251.1
		Switch Chr AAEX03018827.1
		Switch Chr JH373258.1
		Switch Chr JH373278.1
		Switch Chr JH373256.1
		Switch Chr JH373255.1
		Switch Chr JH373259.1
		Switch Chr JH373257.1
		Switch Chr JH373261.1
		Switch Chr JH373262.1
		Switch Chr JH373263.1
		Switch Chr JH373268.1
		Switch Chr JH373281.1
		Switch Chr JH373264.1
		Switch Chr JH373284.1
		Switch Chr JH373267.1
		Switch Chr JH373266.1
		Switch Chr JH373269.1
		Switch Chr JH373336.1
		Switch Chr JH373273.1
		Switch Chr JH373272.1
		Switch Chr JH373270.1
		Switch Chr JH373271.1
		Switch Chr JH373335.1
		Switch Chr JH373371.1
		Switch Chr JH373276.1
		Switch Chr JH373274.1
		Switch Chr JH373275.1
		Switch Chr JH373277.1
		Switch Chr JH373280.1
		Switch Chr AAEX03019065.1
		Switch Chr JH373290.1
		Switch Chr JH373286.1
		Switch Chr JH373279.1
		Switch Chr AAEX03019090.1
		Switch Chr JH373283.1
		Switch Chr JH373282.1
		Switch Chr AAEX03019097.1
		Switch Chr JH373287.1
		Switch Chr JH373288.1
		Switch Chr JH373285.1
		Switch Chr JH373289.1
		Switch Chr JH373291.1
		Switch Chr JH373292.1
		Switch Chr JH373293.1
		Switch Chr JH373294.1
		Switch Chr JH373295.1
		Switch Chr JH373306.1
		Switch Chr JH373296.1
		Switch Chr JH373299.1
		Switch Chr JH373298.1
		Switch Chr JH373297.1
		Switch Chr AAEX03019222.1
		Switch Chr AAEX03019231.1
		Switch Chr JH373304.1
		Switch Chr JH373300.1
		Switch Chr JH373303.1
		Switch Chr AAEX03019240.1
		Switch Chr JH373315.1
		Switch Chr JH373302.1
		Switch Chr JH373301.1
		Switch Chr AAEX03019241.1
		Switch Chr JH373319.1
		Switch Chr JH373307.1
		Switch Chr JH373305.1
		Switch Chr JH373316.1
		Switch Chr JH373308.1
		Switch Chr JH373310.1
		Switch Chr AAEX03019307.1
		Switch Chr JH373313.1
		Switch Chr JH373309.1
		Switch Chr JH373311.1
		Switch Chr JH373330.1
		Switch Chr JH373318.1
		Switch Chr JH373312.1
		Switch Chr AAEX03019339.1
		Switch Chr AAEX03019340.1
		Switch Chr JH373350.1
		Switch Chr AAEX03019341.1
		Switch Chr JH373314.1
		Switch Chr JH373324.1
		Switch Chr JH373332.1
		Switch Chr JH373321.1
		Switch Chr JH373317.1
		Switch Chr JH373320.1
		Switch Chr JH373344.1
		Switch Chr JH373348.1
		Switch Chr JH373322.1
		Switch Chr JH373327.1
		Switch Chr JH373325.1
		Switch Chr JH373323.1
		Switch Chr JH373367.1
		Switch Chr JH373326.1
		Switch Chr JH373376.1
		Switch Chr JH373443.1
		Switch Chr JH373341.1
		Switch Chr JH373394.1
		Switch Chr JH373343.1
		Switch Chr JH373380.1
		Switch Chr JH373366.1
		Switch Chr AAEX03019443.1
		Switch Chr JH373361.1
		Switch Chr JH373334.1
		Switch Chr JH373328.1
		Switch Chr JH373329.1
		Switch Chr JH373362.1
		Switch Chr JH373432.1
		Switch Chr JH373355.1
		Switch Chr JH373389.1
		Switch Chr AAEX03019490.1
		Switch Chr JH373342.1
		Switch Chr AAEX03019491.1
		Switch Chr JH373331.1
		Switch Chr JH373333.1
		Switch Chr JH373337.1
		Switch Chr AAEX03019492.1
		Switch Chr JH373356.1
		Switch Chr AAEX03019535.1
		Switch Chr JH373345.1
		Switch Chr JH373346.1
		Switch Chr JH373354.1
		Switch Chr JH373340.1
		Switch Chr JH373351.1
		Switch Chr AAEX03019548.1
		Switch Chr AAEX03019560.1
		Switch Chr JH373339.1
		Switch Chr JH373338.1
		Switch Chr JH373414.1
		Switch Chr JH373412.1
		Switch Chr JH373347.1
		Switch Chr JH373353.1
		Switch Chr JH373419.1
		Switch Chr JH373349.1
		Switch Chr JH373352.1
		Switch Chr JH373383.1
		Switch Chr JH373382.1
		Switch Chr JH373427.1
		Switch Chr JH373368.1
		Switch Chr JH373421.1
		Switch Chr JH373446.1
		Switch Chr JH373396.1
		Switch Chr JH373370.1
		Switch Chr JH373477.1
		Switch Chr JH373387.1
		Switch Chr JH373357.1
		Switch Chr JH373409.1
		Switch Chr AAEX03019681.1
		Switch Chr JH373503.1
		Switch Chr JH373451.1
		Switch Chr AAEX03019691.1
		Switch Chr JH373358.1
		Switch Chr JH373400.1
		Switch Chr JH373365.1
		Switch Chr JH373494.1
		Switch Chr JH373422.1
		Switch Chr JH373359.1
		Switch Chr JH373385.1
		Switch Chr AAEX03019738.1
		Switch Chr JH373360.1
		Switch Chr JH373364.1
		Switch Chr AAEX03019763.1
		Switch Chr JH373363.1
		Switch Chr JH373391.1
		Switch Chr JH373467.1
		Switch Chr JH373369.1
		Switch Chr JH373372.1
		Switch Chr JH373424.1
		Switch Chr JH373480.1
		Switch Chr JH373476.1
		Switch Chr JH373407.1
		Switch Chr JH373378.1
		Switch Chr JH373386.1
		Switch Chr JH373374.1
		Switch Chr JH373373.1
		Switch Chr JH373375.1
		Switch Chr JH373377.1
		Switch Chr JH373379.1
		Switch Chr JH373442.1
		Switch Chr AAEX03019872.1
		Switch Chr JH373384.1
		Switch Chr AAEX03019893.1
		Switch Chr JH373408.1
		Switch Chr JH373473.1
		Switch Chr JH373505.1
		Switch Chr JH373393.1
		Switch Chr JH373425.1
		Switch Chr JH373390.1
		Switch Chr JH373474.1
		Switch Chr JH373445.1
		Switch Chr JH373388.1
		Switch Chr JH373398.1
		Switch Chr JH373411.1
		Switch Chr JH373420.1
		Switch Chr JH373540.1
		Switch Chr JH373450.1
		Switch Chr JH373452.1
		Switch Chr JH373397.1
		Switch Chr JH373392.1
		Switch Chr JH373481.1
		Switch Chr JH373438.1
		Switch Chr JH373401.1
		Switch Chr JH373395.1
		Switch Chr JH373439.1
		Switch Chr AAEX03019987.1
		Switch Chr JH373527.1
		Switch Chr JH373549.1
		Switch Chr JH373418.1
		Switch Chr JH373745.1
		Switch Chr JH373405.1
		Switch Chr JH373512.1
		Switch Chr JH373399.1
		Switch Chr JH373496.1
		Switch Chr JH373524.1
		Switch Chr JH373416.1
		Switch Chr JH373402.1
		Switch Chr AAEX03020051.1
		Switch Chr JH373417.1
		Switch Chr JH373475.1
		Switch Chr JH373403.1
		Switch Chr AAEX03020054.1
		Switch Chr JH373517.1
		Switch Chr JH373433.1
		Switch Chr AAEX03020055.1
		Switch Chr AAEX03020056.1
		Switch Chr JH373501.1
		Switch Chr JH373568.1
		Switch Chr JH373521.1
		Switch Chr JH373490.1
		Switch Chr JH373468.1
		Switch Chr JH373435.1
		Switch Chr JH373404.1
		Switch Chr AAEX03020060.1
		Switch Chr JH373588.1
		Switch Chr JH373479.1
		Switch Chr AAEX03020068.1
		Switch Chr JH373622.1
		Switch Chr JH373410.1
		Switch Chr AAEX03020105.1
		Switch Chr JH373681.1
		Switch Chr JH373415.1
		Switch Chr JH373413.1
		Switch Chr JH373434.1
		Switch Chr JH373423.1
		Switch Chr JH373430.1
		Switch Chr AAEX03020161.1
		Switch Chr JH373465.1
		Switch Chr JH373566.1
		Switch Chr JH373548.1
		Switch Chr JH373461.1
		Switch Chr AAEX03020170.1
		Switch Chr JH373558.1
		Switch Chr JH373457.1
		Switch Chr JH373614.1
		Switch Chr JH373464.1
		Switch Chr JH373426.1
		Switch Chr JH373444.1
		Switch Chr JH373526.1
		Switch Chr JH373610.1
		Switch Chr JH373460.1
		Switch Chr JH373429.1
		Switch Chr AAEX03020242.1
		Switch Chr JH373488.1
		Switch Chr JH374024.1
		Switch Chr JH373472.1
		Switch Chr JH373695.1
		Switch Chr JH373463.1
		Switch Chr JH373431.1
		Switch Chr JH373440.1
		Switch Chr JH373604.1
		Switch Chr JH373441.1
		Switch Chr JH373478.1
		Switch Chr JH373437.1
		Switch Chr AAEX03020335.1
		Switch Chr JH373449.1
		Switch Chr JH373454.1
		Switch Chr JH373447.1
		Switch Chr JH373453.1
		Switch Chr JH373462.1
		Switch Chr AAEX03020381.1
		Switch Chr JH373703.1
		Switch Chr JH373519.1
		Switch Chr AAEX03020403.1
		Switch Chr JH373532.1
		Switch Chr JH373448.1
		Switch Chr JH373513.1
		Switch Chr JH373623.1
		Switch Chr AAEX03020427.1
		Switch Chr JH373580.1
		Switch Chr JH373507.1
		Switch Chr AAEX03020436.1
		Switch Chr JH373471.1
		Switch Chr JH373613.1
		Switch Chr JH373542.1
		Switch Chr JH373487.1
		Switch Chr JH373455.1
		Switch Chr JH373456.1
		Switch Chr AAEX03020482.1
		Switch Chr JH373576.1
		Switch Chr JH373459.1
		Switch Chr AAEX03020487.1
		Switch Chr JH373575.1
		Switch Chr JH373466.1
		Switch Chr AAEX03020497.1
		Switch Chr JH373644.1
		Switch Chr JH373489.1
		Switch Chr JH373469.1
		Switch Chr JH373529.1
		Switch Chr JH373731.1
		Switch Chr AAEX03020524.1
		Switch Chr JH373528.1
		Switch Chr JH373643.1
		Switch Chr JH373470.1
		Switch Chr AAEX03020533.1
		Switch Chr JH373807.1
		Switch Chr JH373626.1
		Switch Chr JH373486.1
		Switch Chr AAEX03020568.1
		Switch Chr JH373572.1
		Switch Chr JH373569.1
		Switch Chr JH373732.1
		Switch Chr JH373840.1
		Switch Chr JH373541.1
		Switch Chr JH373571.1
		Switch Chr AAEX03020574.1
		Switch Chr JH373624.1
		Switch Chr AAEX03020588.1
		Switch Chr JH373499.1
		Switch Chr AAEX03020610.1
		Switch Chr JH373484.1
		Switch Chr JH373573.1
		Switch Chr JH373504.1
		Switch Chr JH373485.1
		Switch Chr JH373754.1
		Switch Chr JH373672.1
		Switch Chr JH373663.1
		Switch Chr JH373483.1
		Switch Chr JH373538.1
		Switch Chr JH373482.1
		Switch Chr JH373593.1
		Switch Chr JH373497.1
		Switch Chr AAEX03020671.1
		Switch Chr JH373493.1
		Switch Chr JH373724.1
		Switch Chr JH373551.1
		Switch Chr JH373670.1
		Switch Chr AAEX03020700.1
		Switch Chr AAEX03020701.1
		Switch Chr JH373664.1
		Switch Chr JH373609.1
		Switch Chr JH373649.1
		Switch Chr JH373630.1
		Switch Chr JH373607.1
		Switch Chr JH373570.1
		Switch Chr JH373660.1
		Switch Chr JH373646.1
		Switch Chr JH373508.1
		Switch Chr AAEX03020729.1
		Switch Chr JH373506.1
		Switch Chr JH373495.1
		Switch Chr JH373666.1
		Switch Chr JH373492.1
		Switch Chr JH373491.1
		Switch Chr JH373525.1
		Switch Chr JH373602.1
		Switch Chr JH373514.1
		Switch Chr AAEX03020760.1
		Switch Chr JH373611.1
		Switch Chr AAEX03020761.1
		Switch Chr JH373510.1
		Switch Chr JH373502.1
		Switch Chr JH373714.1
		Switch Chr JH373523.1
		Switch Chr JH373516.1
		Switch Chr AAEX03020831.1
		Switch Chr JH373777.1
		Switch Chr JH373650.1
		Switch Chr JH373654.1
		Switch Chr AAEX03020839.1
		Switch Chr JH373564.1
		Switch Chr AAEX03020840.1
		Switch Chr JH373578.1
		Switch Chr JH373638.1
		Switch Chr JH373511.1
		Switch Chr JH373518.1
		Switch Chr JH373645.1
		Switch Chr JH373605.1
		Switch Chr JH373687.1
		Switch Chr JH373543.1
		Switch Chr JH373774.1
		Switch Chr JH373581.1
		Switch Chr JH373509.1
		Switch Chr JH373641.1
		Switch Chr JH373744.1
		Switch Chr JH373515.1
		Switch Chr JH373674.1
		Switch Chr JH373675.1
		Switch Chr AAEX03020896.1
		Switch Chr JH373546.1
		Switch Chr JH373531.1
		Switch Chr JH373554.1
		Switch Chr JH373758.1
		Switch Chr AAEX03020910.1
		Switch Chr JH373522.1
		Switch Chr JH373747.1
		Switch Chr JH373552.1
		Switch Chr JH373718.1
		Switch Chr AAEX03020926.1
		Switch Chr JH373621.1
		Switch Chr JH373534.1
		Switch Chr JH373530.1
		Switch Chr JH373702.1
		Switch Chr JH373757.1
		Switch Chr AAEX03020959.1
		Switch Chr AAEX03020963.1
		Switch Chr JH373595.1
		Switch Chr JH373537.1
		Switch Chr JH373612.1
		Switch Chr JH373710.1
		Switch Chr AAEX03020982.1
		Switch Chr JH373677.1
		Switch Chr JH373616.1
		Switch Chr AAEX03020983.1
		Switch Chr JH373535.1
		Switch Chr JH373956.1
		Switch Chr JH373533.1
		Switch Chr JH373683.1
		Switch Chr AAEX03021041.1
		Switch Chr AAEX03021042.1
		Switch Chr JH373597.1
		Switch Chr AAEX03021043.1
		Switch Chr JH373539.1
		Switch Chr AAEX03021044.1
		Switch Chr JH373553.1
		Switch Chr JH373653.1
		Switch Chr AAEX03021070.1
		Switch Chr JH373787.1
		Switch Chr JH373562.1
		Switch Chr AAEX03021071.1
		Switch Chr AAEX03021077.1
		Switch Chr AAEX03021094.1
		Switch Chr JH373642.1
		Switch Chr AAEX03021108.1
		Switch Chr JH373550.1
		Switch Chr JH373547.1
		Switch Chr JH373723.1
		Switch Chr JH373600.1
		Switch Chr JH373647.1
		Switch Chr AAEX03021139.1
		Switch Chr JH373555.1
		Switch Chr JH373565.1
		Switch Chr JH373606.1
		Switch Chr JH373563.1
		Switch Chr JH373557.1
		Switch Chr AAEX03021187.1
		Switch Chr JH373559.1
		Switch Chr JH373617.1
		Switch Chr AAEX03021193.1
		Switch Chr AAEX03021208.1
		Switch Chr JH373619.1
		Switch Chr JH373561.1
		Switch Chr JH373601.1
		Switch Chr JH373639.1
		Switch Chr JH373830.1
		Switch Chr JH373721.1
		Switch Chr AAEX03021227.1
		Switch Chr JH373793.1
		Switch Chr JH373692.1
		Switch Chr JH373746.1
		Switch Chr JH373567.1
		Switch Chr AAEX03021268.1
		Switch Chr JH373699.1
		Switch Chr JH373598.1
		Switch Chr AAEX03021281.1
		Switch Chr JH373694.1
		Switch Chr AAEX03021282.1
		Switch Chr JH373585.1
		Switch Chr AAEX03021317.1
		Switch Chr AAEX03021318.1
		Switch Chr JH373658.1
		Switch Chr JH373582.1
		Switch Chr JH373713.1
		Switch Chr JH373817.1
		Switch Chr JH373782.1
		Switch Chr JH373579.1
		Switch Chr JH373685.1
		Switch Chr AAEX03021345.1
		Switch Chr AAEX03021372.1
		Switch Chr JH373704.1
		Switch Chr JH373629.1
		Switch Chr JH373583.1
		Switch Chr JH373784.1
		Switch Chr JH373584.1
		Switch Chr JH373785.1
		Switch Chr JH373753.1
		Switch Chr JH373608.1
		Switch Chr JH373586.1
		Switch Chr JH373591.1
		Switch Chr JH373635.1
		Switch Chr JH373603.1
		Switch Chr AAEX03021408.1
		Switch Chr JH373596.1
		Switch Chr JH373592.1
		Switch Chr JH373802.1
		Switch Chr AAEX03021437.1
		Switch Chr AAEX03021458.1
		Switch Chr JH373686.1
		Switch Chr AAEX03021463.1
		Switch Chr JH373655.1
		Switch Chr JH373640.1
		Switch Chr JH373853.1
		Switch Chr AAEX03021489.1
		Switch Chr JH374045.1
		Switch Chr AAEX03021504.1
		Switch Chr JH373893.1
		Switch Chr JH373712.1
		Switch Chr JH373727.1
		Switch Chr JH373689.1
		Switch Chr JH373799.1
		Switch Chr JH373652.1
		Switch Chr AAEX03021540.1
		Switch Chr JH373615.1
		Switch Chr JH373719.1
		Switch Chr JH373618.1
		Switch Chr JH373876.1
		Switch Chr JH373859.1
		Switch Chr AAEX03021579.1
		Switch Chr JH373706.1
		Switch Chr JH373759.1
		Switch Chr AAEX03021599.1
		Switch Chr JH373738.1
		Switch Chr JH373627.1
		Switch Chr AAEX03021648.1
		Switch Chr JH373632.1
		Switch Chr AAEX03021649.1
		Switch Chr AAEX03021660.1
		Switch Chr JH373716.1
		Switch Chr JH373631.1
		Switch Chr JH373735.1
		Switch Chr JH373867.1
		Switch Chr AAEX03021682.1
		Switch Chr JH373892.1
		Switch Chr JH373656.1
		Switch Chr JH373707.1
		Switch Chr JH373637.1
		Switch Chr JH373781.1
		Switch Chr AAEX03021701.1
		Switch Chr JH373636.1
		Switch Chr JH373990.1
		Switch Chr AAEX03021719.1
		Switch Chr JH373763.1
		Switch Chr JH373760.1
		Switch Chr JH373680.1
		Switch Chr JH373798.1
		Switch Chr AAEX03021736.1
		Switch Chr AAEX03021737.1
		Switch Chr JH373749.1
		Switch Chr JH373671.1
		Switch Chr AAEX03021761.1
		Switch Chr JH373832.1
		Switch Chr JH373878.1
		Switch Chr JH373797.1
		Switch Chr JH373743.1
		Switch Chr JH373682.1
		Switch Chr JH373668.1
		Switch Chr AAEX03021790.1
		Switch Chr AAEX03021800.1
		Switch Chr AAEX03021807.1
		Switch Chr JH373887.1
		Switch Chr JH373775.1
		Switch Chr AAEX03021822.1
		Switch Chr JH373690.1
		Switch Chr JH373809.1
		Switch Chr AAEX03021841.1
		Switch Chr AAEX03021842.1
		Switch Chr JH373691.1
		Switch Chr JH373963.1
		Switch Chr JH373657.1
		Switch Chr AAEX03021849.1
		Switch Chr AAEX03021853.1
		Switch Chr AAEX03021854.1
		Switch Chr JH373678.1
		Switch Chr JH373665.1
		Switch Chr JH373698.1
		Switch Chr JH373659.1
		Switch Chr JH373829.1
		Switch Chr JH373679.1
		Switch Chr JH373873.1
		Switch Chr AAEX03021919.1
		Switch Chr JH373705.1
		Switch Chr AAEX03021932.1
		Switch Chr JH373856.1
		Switch Chr JH373676.1
		Switch Chr JH373684.1
		Switch Chr JH373820.1
		Switch Chr JH373858.1
		Switch Chr JH373904.1
		Switch Chr JH373863.1
		Switch Chr AAEX03021979.1
		Switch Chr AAEX03021981.1
		Switch Chr JH373986.1
		Switch Chr JH373688.1
		Switch Chr JH373917.1
		Switch Chr JH373701.1
		Switch Chr AAEX03022003.1
		Switch Chr AAEX03022020.1
		Switch Chr JH373768.1
		Switch Chr AAEX03022031.1
		Switch Chr JH373733.1
		Switch Chr AAEX03022032.1
		Switch Chr JH373700.1
		Switch Chr AAEX03022033.1
		Switch Chr JH373693.1
		Switch Chr AAEX03022043.1
		Switch Chr AAEX03022044.1
		Switch Chr JH373708.1
		Switch Chr AAEX03022057.1
		Switch Chr JH373907.1
		Switch Chr AAEX03022060.1
		Switch Chr JH373839.1
		Switch Chr JH373882.1
		Switch Chr AAEX03022061.1
		Switch Chr AAEX03022063.1
		Switch Chr JH373805.1
		Switch Chr JH373946.1
		Switch Chr JH373734.1
		Switch Chr AAEX03022069.1
		Switch Chr JH373779.1
		Switch Chr JH373836.1
		Switch Chr AAEX03022082.1
		Switch Chr AAEX03022083.1
		Switch Chr JH373756.1
		Switch Chr JH373697.1
		Switch Chr JH373875.1
		Switch Chr AAEX03022093.1
		Switch Chr JH373728.1
		Switch Chr JH373844.1
		Switch Chr JH373750.1
		Switch Chr AAEX03022122.1
		Switch Chr AAEX03022123.1
		Switch Chr JH373717.1
		Switch Chr JH373709.1
		Switch Chr AAEX03022139.1
		Switch Chr JH373790.1
		Switch Chr AAEX03022140.1
		Switch Chr AAEX03022141.1
		Switch Chr JH373715.1
		Switch Chr JH373778.1
		Switch Chr JH373761.1
		Switch Chr AAEX03022149.1
		Switch Chr JH373847.1
		Switch Chr JH373726.1
		Switch Chr AAEX03022157.1
		Switch Chr JH373767.1
		Switch Chr AAEX03022171.1
		Switch Chr JH373736.1
		Switch Chr JH373737.1
		Switch Chr AAEX03022189.1
		Switch Chr AAEX03022193.1
		Switch Chr JH373730.1
		Switch Chr JH373740.1
		Switch Chr AAEX03022194.1
		Switch Chr AAEX03022202.1
		Switch Chr JH373886.1
		Switch Chr AAEX03022203.1
		Switch Chr AAEX03022204.1
		Switch Chr AAEX03022211.1
		Switch Chr AAEX03022212.1
		Switch Chr JH373993.1
		Switch Chr JH374006.1
		Switch Chr AAEX03022216.1
		Switch Chr JH373825.1
		Switch Chr JH373923.1
		Switch Chr JH373855.1
		Switch Chr JH373764.1
		Switch Chr AAEX03022223.1
		Switch Chr JH373964.1
		Switch Chr JH373925.1
		Switch Chr JH373722.1
		Switch Chr AAEX03022239.1
		Switch Chr AAEX03022240.1
		Switch Chr JH373826.1
		Switch Chr JH373765.1
		Switch Chr AAEX03022241.1
		Switch Chr JH373752.1
		Switch Chr AAEX03022242.1
		Switch Chr AAEX03022243.1
		Switch Chr AAEX03022244.1
		Switch Chr JH373811.1
		Switch Chr AAEX03022256.1
		Switch Chr JH373932.1
		Switch Chr AAEX03022262.1
		Switch Chr JH373739.1
		Switch Chr AAEX03022277.1
		Switch Chr JH373981.1
		Switch Chr AAEX03022291.1
		Switch Chr JH373751.1
		Switch Chr JH373788.1
		Switch Chr AAEX03022299.1
		Switch Chr AAEX03022301.1
		Switch Chr AAEX03022317.1
		Switch Chr JH373914.1
		Switch Chr JH373841.1
		Switch Chr AAEX03022329.1
		Switch Chr JH373755.1
		Switch Chr JH373741.1
		Switch Chr AAEX03022332.1
		Switch Chr AAEX03022348.1
		Switch Chr AAEX03022357.1
		Switch Chr AAEX03022358.1
		Switch Chr AAEX03022359.1
		Switch Chr JH373748.1
		Switch Chr AAEX03022378.1
		Switch Chr AAEX03022381.1
		Switch Chr AAEX03022384.1
		Switch Chr AAEX03022390.1
		Switch Chr AAEX03022391.1
		Switch Chr JH373846.1
		Switch Chr JH373791.1
		Switch Chr JH373795.1
		Switch Chr JH373850.1
		Switch Chr JH373772.1
		Switch Chr AAEX03022441.1
		Switch Chr AAEX03022448.1
		Switch Chr JH373818.1
		Switch Chr AAEX03022474.1
		Switch Chr AAEX03022475.1
		Switch Chr JH373770.1
		Switch Chr JH373941.1
		Switch Chr AAEX03022476.1
		Switch Chr AAEX03022477.1
		Switch Chr JH373783.1
		Switch Chr AAEX03022489.1
		Switch Chr JH373822.1
		Switch Chr JH373771.1
		Switch Chr AAEX03022496.1
		Switch Chr JH374067.1
		Switch Chr JH373888.1
		Switch Chr JH373810.1
		Switch Chr JH373801.1
		Switch Chr JH373794.1
		Switch Chr AAEX03022555.1
		Switch Chr JH373843.1
		Switch Chr JH374061.1
		Switch Chr AAEX03022578.1
		Switch Chr AAEX03022579.1
		Switch Chr AAEX03022582.1
		Switch Chr AAEX03022592.1
		Switch Chr AAEX03022606.1
		Switch Chr JH373930.1
		Switch Chr JH373861.1
		Switch Chr JH374017.1
		Switch Chr AAEX03022651.1
		Switch Chr JH373900.1
		Switch Chr JH373824.1
		Switch Chr AAEX03022659.1
		Switch Chr JH373982.1
		Switch Chr JH373934.1
		Switch Chr JH373889.1
		Switch Chr JH373937.1
		Switch Chr JH373935.1
		Switch Chr JH373808.1
		Switch Chr JH373814.1
		Switch Chr JH373819.1
		Switch Chr AAEX03022692.1
		Switch Chr JH373816.1
		Switch Chr JH374004.1
		Switch Chr AAEX03022706.1
		Switch Chr JH373815.1
		Switch Chr AAEX03022707.1
		Switch Chr AAEX03022712.1
		Switch Chr JH373891.1
		Switch Chr AAEX03022713.1
		Switch Chr JH373921.1
		Switch Chr AAEX03022724.1
		Switch Chr JH373821.1
		Switch Chr AAEX03022735.1
		Switch Chr AAEX03022738.1
		Switch Chr AAEX03022739.1
		Switch Chr JH373898.1
		Switch Chr AAEX03022740.1
		Switch Chr AAEX03022741.1
		Switch Chr AAEX03022742.1
		Switch Chr JH373879.1
		Switch Chr AAEX03022744.1
		Switch Chr AAEX03022754.1
		Switch Chr AAEX03022755.1
		Switch Chr AAEX03022756.1
		Switch Chr JH373849.1
		Switch Chr JH373939.1
		Switch Chr JH373950.1
		Switch Chr JH373978.1
		Switch Chr AAEX03022760.1
		Switch Chr AAEX03022761.1
		Switch Chr AAEX03022764.1
		Switch Chr JH373928.1
		Switch Chr JH373915.1
		Switch Chr AAEX03022777.1
		Switch Chr JH374038.1
		Switch Chr JH373949.1
		Switch Chr AAEX03022785.1
		Switch Chr JH373975.1
		Switch Chr AAEX03022786.1
		Switch Chr AAEX03022787.1
		Switch Chr AAEX03022788.1
		Switch Chr JH373884.1
		Switch Chr AAEX03022814.1
		Switch Chr JH373880.1
		Switch Chr JH373851.1
		Switch Chr AAEX03022820.1
		Switch Chr AAEX03022821.1
		Switch Chr JH374053.1
		Switch Chr JH373972.1
		Switch Chr AAEX03022848.1
		Switch Chr AAEX03022849.1
		Switch Chr AAEX03022858.1
		Switch Chr JH373911.1
		Switch Chr JH373842.1
		Switch Chr AAEX03022862.1
		Switch Chr AAEX03022863.1
		Switch Chr JH373890.1
		Switch Chr AAEX03022877.1
		Switch Chr AAEX03022878.1
		Switch Chr JH373954.1
		Switch Chr AAEX03022890.1
		Switch Chr AAEX03022907.1
		Switch Chr AAEX03022908.1
		Switch Chr JH374065.1
		Switch Chr AAEX03022909.1
		Switch Chr JH373872.1
		Switch Chr JH373857.1
		Switch Chr JH373874.1
		Switch Chr JH373869.1
		Switch Chr JH373967.1
		Switch Chr AAEX03022915.1
		Switch Chr JH373916.1
		Switch Chr JH374104.1
		Switch Chr JH373973.1
		Switch Chr AAEX03022941.1
		Switch Chr AAEX03022944.1
		Switch Chr AAEX03022945.1
		Switch Chr JH373894.1
		Switch Chr AAEX03022980.1
		Switch Chr JH373885.1
		Switch Chr JH373948.1
		Switch Chr JH373966.1
		Switch Chr JH374027.1
		Switch Chr JH373918.1
		Switch Chr AAEX03022992.1
		Switch Chr JH373983.1
		Switch Chr JH374001.1
		Switch Chr JH373868.1
		Switch Chr AAEX03022993.1
		Switch Chr JH373933.1
		Switch Chr JH374089.1
		Switch Chr AAEX03023018.1
		Switch Chr AAEX03023030.1
		Switch Chr JH373929.1
		Switch Chr JH374039.1
		Switch Chr AAEX03023045.1
		Switch Chr AAEX03023050.1
		Switch Chr AAEX03023060.1
		Switch Chr JH373974.1
		Switch Chr JH373881.1
		Switch Chr AAEX03023077.1
		Switch Chr JH373947.1
		Switch Chr JH374016.1
		Switch Chr AAEX03023081.1
		Switch Chr AAEX03023082.1
		Switch Chr JH374095.1
		Switch Chr AAEX03023083.1
		Switch Chr AAEX03023097.1
		Switch Chr JH373920.1
		Switch Chr JH373902.1
		Switch Chr JH374002.1
		Switch Chr AAEX03023107.1
		Switch Chr AAEX03023110.1
		Switch Chr JH373970.1
		Switch Chr JH373977.1
		Switch Chr JH374008.1
		Switch Chr JH374015.1
		Switch Chr JH373895.1
		Switch Chr JH373979.1
		Switch Chr JH374020.1
		Switch Chr AAEX03023156.1
		Switch Chr JH374021.1
		Switch Chr JH373969.1
		Switch Chr AAEX03023161.1
		Switch Chr AAEX03023169.1
		Switch Chr AAEX03023172.1
		Switch Chr JH374049.1
		Switch Chr AAEX03023173.1
		Switch Chr JH373962.1
		Switch Chr JH374011.1
		Switch Chr JH373926.1
		Switch Chr AAEX03023177.1
		Switch Chr JH373905.1
		Switch Chr JH373919.1
		Switch Chr AAEX03023201.1
		Switch Chr AAEX03023211.1
		Switch Chr JH373927.1
		Switch Chr AAEX03023212.1
		Switch Chr JH374047.1
		Switch Chr AAEX03023213.1
		Switch Chr JH373961.1
		Switch Chr JH374063.1
		Switch Chr AAEX03023229.1
		Switch Chr JH373922.1
		Switch Chr AAEX03023233.1
		Switch Chr AAEX03023234.1
		Switch Chr JH373936.1
		Switch Chr AAEX03023240.1
		Switch Chr JH374055.1
		Switch Chr JH374050.1
		Switch Chr AAEX03023257.1
		Switch Chr AAEX03023258.1
		Switch Chr JH373931.1
		Switch Chr JH374022.1
		Switch Chr AAEX03023275.1
		Switch Chr AAEX03023286.1
		Switch Chr AAEX03023291.1
		Switch Chr JH374026.1
		Switch Chr JH373938.1
		Switch Chr AAEX03023315.1
		Switch Chr JH373951.1
		Switch Chr AAEX03023323.1
		Switch Chr AAEX03023324.1
		Switch Chr JH373988.1
		Switch Chr JH373942.1
		Switch Chr JH374071.1
		Switch Chr JH374081.1
		Switch Chr JH373995.1
		Switch Chr JH373959.1
		Switch Chr JH374029.1
		Switch Chr AAEX03023347.1
		Switch Chr JH374041.1
		Switch Chr AAEX03023355.1
		Switch Chr AAEX03023356.1
		Switch Chr AAEX03023357.1
		Switch Chr AAEX03023358.1
		Switch Chr AAEX03023365.1
		Switch Chr AAEX03023366.1
		Switch Chr AAEX03023367.1
		Switch Chr JH373997.1
		Switch Chr JH373953.1
		Switch Chr AAEX03023373.1
		Switch Chr AAEX03023374.1
		Switch Chr AAEX03023381.1
		Switch Chr AAEX03023382.1
		Switch Chr AAEX03023386.1
		Switch Chr JH373958.1
		Switch Chr AAEX03023392.1
		Switch Chr JH374060.1
		Switch Chr JH373976.1
		Switch Chr JH374051.1
		Switch Chr AAEX03023396.1
		Switch Chr JH374149.1
		Switch Chr JH374056.1
		Switch Chr JH374101.1
		Switch Chr JH374079.1
		Switch Chr AAEX03023424.1
		Switch Chr JH374164.1
		Switch Chr AAEX03023426.1
		Switch Chr AAEX03023435.1
		Switch Chr AAEX03023437.1
		Switch Chr JH373984.1
		Switch Chr AAEX03023449.1
		Switch Chr AAEX03023450.1
		Switch Chr AAEX03023452.1
		Switch Chr JH373996.1
		Switch Chr AAEX03023460.1
		Switch Chr AAEX03023468.1
		Switch Chr JH374163.1
		Switch Chr AAEX03023484.1
		Switch Chr AAEX03023485.1
		Switch Chr AAEX03023493.1
		Switch Chr JH374074.1
		Switch Chr AAEX03023504.1
		Switch Chr JH374043.1
		Switch Chr AAEX03023506.1
		Switch Chr AAEX03023507.1
		Switch Chr AAEX03023508.1
		Switch Chr AAEX03023514.1
		Switch Chr AAEX03023518.1
		Switch Chr AAEX03023519.1
		Switch Chr AAEX03023520.1
		Switch Chr JH374019.1
		Switch Chr JH374117.1
		Switch Chr AAEX03023521.1
		Switch Chr AAEX03023522.1
		Switch Chr AAEX03023524.1
		Switch Chr AAEX03023529.1
		Switch Chr JH374091.1
		Switch Chr AAEX03023535.1
		Switch Chr AAEX03023536.1
		Switch Chr AAEX03023537.1
		Switch Chr AAEX03023538.1
		Switch Chr AAEX03023556.1
		Switch Chr JH374154.1
		Switch Chr AAEX03023558.1
		Switch Chr AAEX03023559.1
		Switch Chr AAEX03023563.1
		Switch Chr JH374057.1
		Switch Chr AAEX03023573.1
		Switch Chr AAEX03023576.1
		Switch Chr AAEX03023586.1
		Switch Chr AAEX03023594.1
		Switch Chr JH374109.1
		Switch Chr AAEX03023617.1
		Switch Chr AAEX03023624.1
		Switch Chr JH374166.1
		Switch Chr AAEX03023627.1
		Switch Chr JH374106.1
		Switch Chr AAEX03023640.1
		Switch Chr JH374103.1
		Switch Chr JH374013.1
		Switch Chr AAEX03023651.1
		Switch Chr AAEX03023664.1
		Switch Chr AAEX03023665.1
		Switch Chr JH374007.1
		Switch Chr AAEX03023686.1
		Switch Chr AAEX03023691.1
		Switch Chr AAEX03023693.1
		Switch Chr JH374122.1
		Switch Chr AAEX03023696.1
		Switch Chr JH374136.1
		Switch Chr AAEX03023702.1
		Switch Chr JH374012.1
		Switch Chr JH374130.1
		Switch Chr AAEX03023724.1
		Switch Chr AAEX03023725.1
		Switch Chr JH374058.1
		Switch Chr JH374077.1
		Switch Chr AAEX03023732.1
		Switch Chr AAEX03023735.1
		Switch Chr AAEX03023736.1
		Switch Chr AAEX03023737.1
		Switch Chr AAEX03023742.1
		Switch Chr AAEX03023744.1
		Switch Chr JH374133.1
		Switch Chr AAEX03023755.1
		Switch Chr AAEX03023758.1
		Switch Chr AAEX03023760.1
		Switch Chr JH374146.1
		Switch Chr AAEX03023762.1
		Switch Chr AAEX03023766.1
		Switch Chr AAEX03023767.1
		Switch Chr AAEX03023770.1
		Switch Chr AAEX03023771.1
		Switch Chr AAEX03023772.1
		Switch Chr AAEX03023777.1
		Switch Chr AAEX03023778.1
		Switch Chr AAEX03023779.1
		Switch Chr AAEX03023782.1
		Switch Chr JH374086.1
		Switch Chr AAEX03023784.1
		Switch Chr AAEX03023786.1
		Switch Chr AAEX03023788.1
		Switch Chr AAEX03023794.1
		Switch Chr JH374032.1
		Switch Chr AAEX03023809.1
		Switch Chr JH374124.1
		Switch Chr AAEX03023812.1
		Switch Chr AAEX03023813.1
		Switch Chr JH374111.1
		Switch Chr AAEX03023823.1
		Switch Chr AAEX03023824.1
		Switch Chr AAEX03023825.1
		Switch Chr JH374172.1
		Switch Chr JH374054.1
		Switch Chr AAEX03023828.1
		Switch Chr AAEX03023829.1
		Switch Chr AAEX03023830.1
		Switch Chr AAEX03023832.1
		Switch Chr AAEX03023836.1
		Switch Chr AAEX03023837.1
		Switch Chr AAEX03023840.1
		Switch Chr JH374052.1
		Switch Chr AAEX03023842.1
		Switch Chr AAEX03023848.1
		Switch Chr AAEX03023849.1
		Switch Chr JH374059.1
		Switch Chr JH374107.1
		Switch Chr JH374151.1
		Switch Chr AAEX03023881.1
		Switch Chr AAEX03023882.1
		Switch Chr JH374087.1
		Switch Chr AAEX03023883.1
		Switch Chr AAEX03023884.1
		Switch Chr AAEX03023885.1
		Switch Chr AAEX03023886.1
		Switch Chr AAEX03023887.1
		Switch Chr JH374042.1
		Switch Chr AAEX03023900.1
		Switch Chr JH374152.1
		Switch Chr AAEX03023901.1
		Switch Chr JH374044.1
		Switch Chr AAEX03023913.1
		Switch Chr AAEX03023920.1
		Switch Chr AAEX03023922.1
		Switch Chr AAEX03023923.1
		Switch Chr AAEX03023924.1
		Switch Chr AAEX03023928.1
		Switch Chr AAEX03023929.1
		Switch Chr AAEX03023933.1
		Switch Chr AAEX03023935.1
		Switch Chr AAEX03023940.1
		Switch Chr AAEX03023951.1
		Switch Chr JH374178.1
		Switch Chr AAEX03023968.1
		Switch Chr AAEX03023969.1
		Switch Chr AAEX03023970.1
		Switch Chr AAEX03023980.1
		Switch Chr AAEX03023987.1
		Switch Chr AAEX03023988.1
		Switch Chr AAEX03023990.1
		Switch Chr JH374075.1
		Switch Chr JH374076.1
		Switch Chr AAEX03024006.1
		Switch Chr AAEX03024015.1
		Switch Chr AAEX03024016.1
		Switch Chr JH374121.1
		Switch Chr AAEX03024020.1
		Switch Chr AAEX03024022.1
		Switch Chr JH374085.1
		Switch Chr AAEX03024040.1
		Switch Chr AAEX03024041.1
		Switch Chr AAEX03024049.1
		Switch Chr AAEX03024052.1
		Switch Chr JH374153.1
		Switch Chr AAEX03024063.1
		Switch Chr AAEX03024064.1
		Switch Chr AAEX03024065.1
		Switch Chr JH374143.1
		Switch Chr AAEX03024070.1
		Switch Chr AAEX03024071.1
		Switch Chr AAEX03024072.1
		Switch Chr JH374099.1
		Switch Chr JH374098.1
		Switch Chr AAEX03024075.1
		Switch Chr AAEX03024083.1
		Switch Chr AAEX03024084.1
		Switch Chr AAEX03024088.1
		Switch Chr AAEX03024089.1
		Switch Chr AAEX03024092.1
		Switch Chr AAEX03024096.1
		Switch Chr AAEX03024097.1
		Switch Chr AAEX03024100.1
		Switch Chr AAEX03024108.1
		Switch Chr AAEX03024114.1
		Switch Chr AAEX03024115.1
		Switch Chr AAEX03024116.1
		Switch Chr AAEX03024119.1
		Switch Chr AAEX03024120.1
		Switch Chr AAEX03024124.1
		Switch Chr AAEX03024125.1
		Switch Chr AAEX03024126.1
		Switch Chr AAEX03024129.1
		Switch Chr AAEX03024132.1
		Switch Chr JH374161.1
		Switch Chr AAEX03024137.1
		Switch Chr AAEX03024138.1
		Switch Chr JH374083.1
		Switch Chr AAEX03024143.1
		Switch Chr AAEX03024144.1
		Switch Chr AAEX03024151.1
		Switch Chr AAEX03024167.1
		Switch Chr AAEX03024174.1
		Switch Chr JH374127.1
		Switch Chr AAEX03024181.1
		Switch Chr AAEX03024183.1
		Switch Chr AAEX03024185.1
		Switch Chr AAEX03024186.1
		Switch Chr AAEX03024187.1
		Switch Chr AAEX03024188.1
		Switch Chr JH374132.1
		Switch Chr AAEX03024194.1
		Switch Chr JH374140.1
		Switch Chr AAEX03024201.1
		Switch Chr AAEX03024203.1
		Switch Chr AAEX03024206.1
		Switch Chr AAEX03024207.1
		Switch Chr JH374138.1
		Switch Chr AAEX03024209.1
		Switch Chr JH374128.1
		Switch Chr JH374093.1
		Switch Chr AAEX03024210.1
		Switch Chr AAEX03024220.1
		Switch Chr JH374157.1
		Switch Chr AAEX03024224.1
		Switch Chr AAEX03024225.1
		Switch Chr AAEX03024226.1
		Switch Chr AAEX03024227.1
		Switch Chr AAEX03024228.1
		Switch Chr AAEX03024239.1
		Switch Chr AAEX03024243.1
		Switch Chr JH374177.1
		Switch Chr AAEX03024246.1
		Switch Chr AAEX03024247.1
		Switch Chr AAEX03024257.1
		Switch Chr AAEX03024258.1
		Switch Chr AAEX03024261.1
		Switch Chr AAEX03024269.1
		Switch Chr AAEX03024271.1
		Switch Chr AAEX03024274.1
		Switch Chr AAEX03024277.1
		Switch Chr AAEX03024279.1
		Switch Chr JH374131.1
		Switch Chr AAEX03024301.1
		Switch Chr AAEX03024305.1
		Switch Chr AAEX03024306.1
		Switch Chr AAEX03024307.1
		Switch Chr AAEX03024314.1
		Switch Chr AAEX03024316.1
		Switch Chr AAEX03024319.1
		Switch Chr AAEX03024324.1
		Switch Chr AAEX03024326.1
		Switch Chr AAEX03024333.1
		Switch Chr AAEX03024334.1
		Switch Chr AAEX03024336.1
		Switch Chr AAEX03024340.1
		Switch Chr AAEX03024342.1
		Switch Chr JH374144.1
		Switch Chr AAEX03024349.1
		Switch Chr JH374158.1
		Switch Chr AAEX03024357.1
		Switch Chr AAEX03024360.1
		Switch Chr AAEX03024361.1
		Switch Chr AAEX03024362.1
		Switch Chr AAEX03024364.1
		Switch Chr AAEX03024371.1
		Switch Chr AAEX03024377.1
		Switch Chr AAEX03024379.1
		Switch Chr AAEX03024389.1
		Switch Chr AAEX03024390.1
		Switch Chr AAEX03024392.1
		Switch Chr AAEX03024401.1
		Switch Chr AAEX03024404.1
		Switch Chr AAEX03024407.1
		Switch Chr AAEX03024411.1
		Switch Chr AAEX03024414.1
		Switch Chr AAEX03024415.1
		Switch Chr JH374123.1
		Switch Chr AAEX03024419.1
		Switch Chr AAEX03024420.1
		Switch Chr AAEX03024421.1
		Switch Chr AAEX03024422.1
		Switch Chr AAEX03024423.1
		Switch Chr AAEX03024431.1
		Switch Chr AAEX03024439.1
		Switch Chr AAEX03024440.1
		Switch Chr JH374142.1
		Switch Chr AAEX03024444.1
		Switch Chr AAEX03024445.1
		Switch Chr AAEX03024447.1
		Switch Chr AAEX03024451.1
		Switch Chr AAEX03024460.1
		Switch Chr AAEX03024462.1
		Switch Chr AAEX03024467.1
		Switch Chr AAEX03024469.1
		Switch Chr AAEX03024472.1
		Switch Chr AAEX03024478.1
		Switch Chr AAEX03024481.1
		Switch Chr AAEX03024485.1
		Switch Chr AAEX03024486.1
		Switch Chr AAEX03024487.1
		Switch Chr AAEX03024488.1
		Switch Chr JH374181.1
		Switch Chr AAEX03024491.1
		Switch Chr AAEX03024494.1
		Switch Chr AAEX03024495.1
		Switch Chr AAEX03024502.1
		Switch Chr JH374139.1
		Switch Chr AAEX03024509.1
		Switch Chr AAEX03024510.1
		Switch Chr AAEX03024511.1
		Switch Chr AAEX03024512.1
		Switch Chr AAEX03024513.1
		Switch Chr AAEX03024514.1
		Switch Chr AAEX03024515.1
		Switch Chr AAEX03024518.1
		Switch Chr AAEX03024522.1
		Switch Chr AAEX03024523.1
		Switch Chr AAEX03024525.1
		Switch Chr AAEX03024527.1
		Switch Chr AAEX03024536.1
		Switch Chr AAEX03024540.1
		Switch Chr AAEX03024543.1
		Switch Chr AAEX03024545.1
		Switch Chr AAEX03024550.1
		Switch Chr AAEX03024553.1
		Switch Chr AAEX03024556.1
		Switch Chr AAEX03024557.1
		Switch Chr AAEX03024561.1
		Switch Chr AAEX03024562.1
		Switch Chr AAEX03024569.1
		Switch Chr AAEX03024572.1
		Switch Chr AAEX03024574.1
		Switch Chr AAEX03024581.1
		Switch Chr AAEX03024587.1
		Switch Chr AAEX03024592.1
		Switch Chr AAEX03024599.1
		Switch Chr AAEX03024600.1
		Switch Chr AAEX03024608.1
		Switch Chr AAEX03024611.1
		Switch Chr AAEX03024618.1
		Switch Chr AAEX03024619.1
		Switch Chr AAEX03024622.1
		Switch Chr JH374141.1
		Switch Chr AAEX03024633.1
		Switch Chr AAEX03024634.1
		Switch Chr AAEX03024638.1
		Switch Chr AAEX03024639.1
		Switch Chr AAEX03024646.1
		Switch Chr AAEX03024647.1
		Switch Chr AAEX03024649.1
		Switch Chr AAEX03024650.1
		Switch Chr AAEX03024653.1
		Switch Chr AAEX03024654.1
		Switch Chr AAEX03024655.1
		Switch Chr AAEX03024656.1
		Switch Chr AAEX03024659.1
		Switch Chr AAEX03024661.1
		Switch Chr JH374147.1
		Switch Chr AAEX03024664.1
		Switch Chr AAEX03024666.1
		Switch Chr AAEX03024667.1
		Switch Chr AAEX03024668.1
		Switch Chr AAEX03024669.1
		Switch Chr AAEX03024672.1
		Switch Chr JH374156.1
		Switch Chr AAEX03024682.1
		Switch Chr AAEX03024684.1
		Switch Chr JH374189.1
		Switch Chr AAEX03024686.1
		Switch Chr AAEX03024692.1
		Switch Chr AAEX03024695.1
		Switch Chr AAEX03024696.1
		Switch Chr AAEX03024697.1
		Switch Chr AAEX03024698.1
		Switch Chr AAEX03024702.1
		Switch Chr AAEX03024707.1
		Switch Chr AAEX03024709.1
		Switch Chr AAEX03024710.1
		Switch Chr AAEX03024711.1
		Switch Chr AAEX03024713.1
		Switch Chr AAEX03024718.1
		Switch Chr AAEX03024729.1
		Switch Chr AAEX03024730.1
		Switch Chr AAEX03024732.1
		Switch Chr AAEX03024734.1
		Switch Chr AAEX03024735.1
		Switch Chr AAEX03024740.1
		Switch Chr AAEX03024744.1
		Switch Chr AAEX03024745.1
		Switch Chr AAEX03024747.1
		Switch Chr AAEX03024750.1
		Switch Chr AAEX03024753.1
		Switch Chr AAEX03024754.1
		Switch Chr AAEX03024756.1
		Switch Chr AAEX03024757.1
		Switch Chr AAEX03024759.1
		Switch Chr AAEX03024760.1
		Switch Chr AAEX03024762.1
		Switch Chr AAEX03024763.1
		Switch Chr AAEX03024767.1
		Switch Chr AAEX03024768.1
		Switch Chr AAEX03024772.1
		Switch Chr AAEX03024774.1
		Switch Chr AAEX03024776.1
		Switch Chr AAEX03024779.1
		Switch Chr AAEX03024783.1
		Switch Chr AAEX03024784.1
		Switch Chr AAEX03024790.1
		Switch Chr AAEX03024796.1
		Switch Chr AAEX03024804.1
		Switch Chr AAEX03024813.1
		Switch Chr AAEX03024814.1
		Switch Chr AAEX03024815.1
		Switch Chr AAEX03024819.1
		Switch Chr AAEX03024821.1
		Switch Chr AAEX03024824.1
		Switch Chr AAEX03024826.1
		Switch Chr AAEX03024828.1
		Switch Chr AAEX03024829.1
		Switch Chr AAEX03024830.1
		Switch Chr AAEX03024837.1
		Switch Chr AAEX03024839.1
		Switch Chr AAEX03024840.1
		Switch Chr AAEX03024844.1
		Switch Chr AAEX03024847.1
		Switch Chr AAEX03024851.1
		Switch Chr AAEX03024852.1
		Switch Chr AAEX03024860.1
		Switch Chr AAEX03024862.1
		Switch Chr AAEX03024867.1
		Switch Chr AAEX03024871.1
		Switch Chr JH374155.1
		Switch Chr AAEX03024878.1
		Switch Chr AAEX03024879.1
		Switch Chr AAEX03024885.1
		Switch Chr AAEX03024886.1
		Switch Chr AAEX03024890.1
		Switch Chr AAEX03024892.1
		Switch Chr AAEX03024893.1
		Switch Chr AAEX03024894.1
		Switch Chr AAEX03024897.1
		Switch Chr AAEX03024899.1
		Switch Chr AAEX03024902.1
		Switch Chr JH374159.1
		Switch Chr AAEX03024907.1
		Switch Chr AAEX03024909.1
		Switch Chr AAEX03024911.1
		Switch Chr AAEX03024912.1
		Switch Chr AAEX03024913.1
		Switch Chr AAEX03024920.1
		Switch Chr AAEX03024922.1
		Switch Chr AAEX03024927.1
		Switch Chr AAEX03024934.1
		Switch Chr AAEX03024935.1
		Switch Chr AAEX03024936.1
		Switch Chr AAEX03024937.1
		Switch Chr AAEX03024938.1
		Switch Chr JH374175.1
		Switch Chr AAEX03024939.1
		Switch Chr AAEX03024940.1
		Switch Chr AAEX03024948.1
		Switch Chr AAEX03024950.1
		Switch Chr AAEX03024954.1
		Switch Chr AAEX03024955.1
		Switch Chr JH374180.1
		Switch Chr AAEX03024956.1
		Switch Chr AAEX03024961.1
		Switch Chr AAEX03024962.1
		Switch Chr AAEX03024963.1
		Switch Chr AAEX03024964.1
		Switch Chr AAEX03024969.1
		Switch Chr AAEX03024971.1
		Switch Chr AAEX03024974.1
		Switch Chr AAEX03024977.1
		Switch Chr AAEX03024978.1
		Switch Chr AAEX03024980.1
		Switch Chr AAEX03024987.1
		Switch Chr AAEX03024988.1
		Switch Chr AAEX03024990.1
		Switch Chr AAEX03024996.1
		Switch Chr AAEX03025000.1
		Switch Chr AAEX03025005.1
		Switch Chr AAEX03025007.1
		Switch Chr AAEX03025012.1
		Switch Chr AAEX03025013.1
		Switch Chr AAEX03025016.1
		Switch Chr AAEX03025018.1
		Switch Chr AAEX03025020.1
		Switch Chr AAEX03025024.1
		Switch Chr AAEX03025025.1
		Switch Chr AAEX03025029.1
		Switch Chr AAEX03025031.1
		Switch Chr AAEX03025036.1
		Switch Chr JH374165.1
		Switch Chr AAEX03025041.1
		Switch Chr AAEX03025048.1
		Switch Chr AAEX03025054.1
		Switch Chr AAEX03025059.1
		Switch Chr AAEX03025060.1
		Switch Chr AAEX03025061.1
		Switch Chr AAEX03025063.1
		Switch Chr AAEX03025064.1
		Switch Chr AAEX03025065.1
		Switch Chr JH374169.1
		Switch Chr AAEX03025066.1
		Switch Chr AAEX03025067.1
		Switch Chr AAEX03025077.1
		Switch Chr AAEX03025079.1
		Switch Chr AAEX03025080.1
		Switch Chr AAEX03025082.1
		Switch Chr AAEX03025084.1
		Switch Chr AAEX03025085.1
		Switch Chr AAEX03025087.1
		Switch Chr AAEX03025091.1
		Switch Chr AAEX03025092.1
		Switch Chr AAEX03025094.1
		Switch Chr AAEX03025097.1
		Switch Chr AAEX03025098.1
		Switch Chr AAEX03025101.1
		Switch Chr AAEX03025102.1
		Switch Chr JH374191.1
		Switch Chr AAEX03025108.1
		Switch Chr AAEX03025109.1
		Switch Chr AAEX03025110.1
		Switch Chr AAEX03025121.1
		Switch Chr AAEX03025123.1
		Switch Chr AAEX03025125.1
		Switch Chr AAEX03025128.1
		Switch Chr AAEX03025132.1
		Switch Chr AAEX03025136.1
		Switch Chr AAEX03025140.1
		Switch Chr AAEX03025141.1
		Switch Chr AAEX03025142.1
		Switch Chr AAEX03025143.1
		Switch Chr AAEX03025144.1
		Switch Chr JH374174.1
		Switch Chr AAEX03025149.1
		Switch Chr AAEX03025151.1
		Switch Chr AAEX03025155.1
		Switch Chr AAEX03025157.1
		Switch Chr AAEX03025158.1
		Switch Chr AAEX03025160.1
		Switch Chr AAEX03025165.1
		Switch Chr JH374176.1
		Switch Chr AAEX03025172.1
		Switch Chr AAEX03025175.1
		Switch Chr AAEX03025181.1
		Switch Chr AAEX03025188.1
		Switch Chr AAEX03025189.1
		Switch Chr AAEX03025190.1
		Switch Chr AAEX03025193.1
		Switch Chr AAEX03025195.1
		Switch Chr AAEX03025203.1
		Switch Chr AAEX03025205.1
		Switch Chr AAEX03025206.1
		Switch Chr AAEX03025209.1
		Switch Chr AAEX03025214.1
		Switch Chr AAEX03025217.1
		Switch Chr AAEX03025220.1
		Switch Chr AAEX03025221.1
		Switch Chr AAEX03025223.1
		Switch Chr AAEX03025226.1
		Switch Chr AAEX03025228.1
		Switch Chr AAEX03025232.1
		Switch Chr AAEX03025238.1
		Switch Chr AAEX03025240.1
		Switch Chr AAEX03025248.1
		Switch Chr AAEX03025250.1
		Switch Chr AAEX03025251.1
		Switch Chr AAEX03025252.1
		Switch Chr AAEX03025254.1
		Switch Chr AAEX03025256.1
		Switch Chr AAEX03025257.1
		Switch Chr AAEX03025258.1
		Switch Chr AAEX03025259.1
		Switch Chr AAEX03025262.1
		Switch Chr AAEX03025265.1
		Switch Chr AAEX03025272.1
		Switch Chr AAEX03025274.1
		Switch Chr AAEX03025275.1
		Switch Chr AAEX03025280.1
		Switch Chr AAEX03025283.1
		Switch Chr AAEX03025285.1
		Switch Chr AAEX03025287.1
		Switch Chr AAEX03025289.1
		Switch Chr AAEX03025293.1
		Switch Chr AAEX03025296.1
		Switch Chr AAEX03025304.1
		Switch Chr AAEX03025307.1
		Switch Chr AAEX03025310.1
		Switch Chr AAEX03025312.1
		Switch Chr AAEX03025320.1
		Switch Chr AAEX03025322.1
		Switch Chr AAEX03025323.1
		Switch Chr AAEX03025324.1
		Switch Chr AAEX03025325.1
		Switch Chr AAEX03025328.1
		Switch Chr AAEX03025330.1
		Switch Chr AAEX03025333.1
		Switch Chr AAEX03025334.1
		Switch Chr AAEX03025335.1
		Switch Chr AAEX03025336.1
		Switch Chr AAEX03025337.1
		Switch Chr AAEX03025347.1
		Switch Chr AAEX03025350.1
		Switch Chr AAEX03025352.1
		Switch Chr AAEX03025353.1
		Switch Chr AAEX03025355.1
		Switch Chr AAEX03025356.1
		Switch Chr AAEX03025358.1
		Switch Chr AAEX03025360.1
		Switch Chr AAEX03025372.1
		Switch Chr AAEX03025377.1
		Switch Chr AAEX03025378.1
		Switch Chr AAEX03025379.1
		Switch Chr AAEX03025385.1
		Switch Chr AAEX03025387.1
		Switch Chr AAEX03025388.1
		Switch Chr AAEX03025394.1
		Switch Chr AAEX03025398.1
		Switch Chr AAEX03025399.1
		Switch Chr AAEX03025400.1
		Switch Chr AAEX03025401.1
		Switch Chr AAEX03025402.1
		Switch Chr AAEX03025408.1
		Switch Chr AAEX03025409.1
		Switch Chr AAEX03025411.1
		Switch Chr AAEX03025415.1
		Switch Chr AAEX03025416.1
		Switch Chr AAEX03025422.1
		Switch Chr AAEX03025424.1
		Switch Chr AAEX03025426.1
		Switch Chr AAEX03025429.1
		Switch Chr AAEX03025431.1
		Switch Chr AAEX03025434.1
		Switch Chr AAEX03025435.1
		Switch Chr AAEX03025437.1
		Switch Chr AAEX03025439.1
		Switch Chr AAEX03025440.1
		Switch Chr AAEX03025441.1
		Switch Chr AAEX03025442.1
		Switch Chr AAEX03025448.1
		Switch Chr AAEX03025453.1
		Switch Chr AAEX03025455.1
		Switch Chr AAEX03025464.1
		Switch Chr AAEX03025469.1
		Switch Chr AAEX03025470.1
		Switch Chr AAEX03025474.1
		Switch Chr AAEX03025486.1
		Switch Chr AAEX03025489.1
		Switch Chr AAEX03025491.1
		Switch Chr AAEX03025495.1
		Switch Chr AAEX03025496.1
		Switch Chr AAEX03025500.1
		Switch Chr AAEX03025502.1
		Switch Chr AAEX03025505.1
		Switch Chr AAEX03025508.1
		Switch Chr AAEX03025509.1
		Switch Chr AAEX03025511.1
		Switch Chr AAEX03025518.1
		Switch Chr AAEX03025523.1
		Switch Chr AAEX03025524.1
		Switch Chr AAEX03025528.1
		Switch Chr AAEX03025530.1
		Switch Chr AAEX03025531.1
		Switch Chr JH374193.1
		Switch Chr AAEX03025540.1
		Switch Chr AAEX03025541.1
		Switch Chr AAEX03025542.1
		Switch Chr AAEX03025543.1
		Switch Chr AAEX03025550.1
		Switch Chr AAEX03025566.1
		Switch Chr AAEX03025569.1
		Switch Chr AAEX03025571.1
		Switch Chr AAEX03025572.1
		Switch Chr AAEX03025581.1
		Switch Chr AAEX03025582.1
		Switch Chr AAEX03025583.1
		Switch Chr AAEX03025586.1
		Switch Chr AAEX03025595.1
		Switch Chr AAEX03025597.1
		Switch Chr AAEX03025602.1
		Switch Chr AAEX03025604.1
		Switch Chr AAEX03025608.1
		Switch Chr AAEX03025612.1
		Switch Chr AAEX03025616.1
		Switch Chr AAEX03025618.1
		Switch Chr AAEX03025619.1
		Switch Chr AAEX03025624.1
		Switch Chr AAEX03025628.1
		Switch Chr AAEX03025629.1
		Switch Chr AAEX03025637.1
		Switch Chr AAEX03025643.1
		Switch Chr AAEX03025644.1
		Switch Chr AAEX03025647.1
		Switch Chr AAEX03025648.1
		Switch Chr AAEX03025658.1
		Switch Chr AAEX03025659.1
		Switch Chr AAEX03025661.1
		Switch Chr AAEX03025665.1
		Switch Chr AAEX03025667.1
		Switch Chr AAEX03025677.1
		Switch Chr AAEX03025679.1
		Switch Chr AAEX03025680.1
		Switch Chr AAEX03025684.1
		Switch Chr AAEX03025686.1
		Switch Chr AAEX03025689.1
		Switch Chr AAEX03025702.1
		Switch Chr AAEX03025704.1
		Switch Chr AAEX03025707.1
		Switch Chr AAEX03025708.1
		Switch Chr AAEX03025712.1
		Switch Chr AAEX03025715.1
		Switch Chr AAEX03025718.1
		Switch Chr AAEX03025721.1
		Switch Chr AAEX03025722.1
		Switch Chr AAEX03025723.1
		Switch Chr AAEX03025726.1
		Switch Chr AAEX03025727.1
		Switch Chr AAEX03025729.1
		Switch Chr AAEX03025730.1
		Switch Chr AAEX03025731.1
		Switch Chr AAEX03025736.1
		Switch Chr AAEX03025737.1
		Switch Chr AAEX03025740.1
		Switch Chr AAEX03025742.1
		Switch Chr AAEX03025743.1
		Switch Chr AAEX03025744.1
		Switch Chr AAEX03025749.1
		Switch Chr AAEX03025751.1
		Switch Chr AAEX03025755.1
		Switch Chr AAEX03025757.1
		Switch Chr AAEX03025767.1
		Switch Chr AAEX03025768.1
		Switch Chr AAEX03025770.1
		Switch Chr AAEX03025771.1
		Switch Chr AAEX03025773.1
		Switch Chr AAEX03025777.1
		Switch Chr AAEX03025778.1
		Switch Chr AAEX03025781.1
		Switch Chr AAEX03025782.1
		Switch Chr AAEX03025787.1
		Switch Chr AAEX03025788.1
		Switch Chr AAEX03025789.1
		Switch Chr AAEX03025792.1
		Switch Chr AAEX03025796.1
		Switch Chr AAEX03025797.1
		Switch Chr AAEX03025800.1
		Switch Chr AAEX03025802.1
		Switch Chr AAEX03025805.1
		Switch Chr AAEX03025810.1
		Switch Chr AAEX03025811.1
		Switch Chr AAEX03025817.1
		Switch Chr AAEX03025820.1
		Switch Chr AAEX03025823.1
		Switch Chr AAEX03025825.1
		Switch Chr AAEX03025826.1
		Switch Chr AAEX03025833.1
		Switch Chr AAEX03025835.1
		Switch Chr AAEX03025836.1
		Switch Chr AAEX03025840.1
		Switch Chr AAEX03025841.1
		Switch Chr AAEX03025842.1
		Switch Chr AAEX03025852.1
		Switch Chr AAEX03025866.1
		Switch Chr AAEX03025873.1
		Switch Chr AAEX03025878.1
		Switch Chr AAEX03025879.1
		Switch Chr AAEX03025881.1
		Switch Chr AAEX03025886.1
		Switch Chr AAEX03025891.1
		Switch Chr AAEX03025892.1
		Switch Chr AAEX03025895.1
		Switch Chr AAEX03025896.1
		Switch Chr AAEX03025902.1
		Switch Chr AAEX03025907.1
		Switch Chr AAEX03025909.1
		Switch Chr AAEX03025910.1
		Switch Chr AAEX03025915.1
		Switch Chr AAEX03025917.1
		Switch Chr AAEX03025918.1
		Switch Chr AAEX03025921.1
		Switch Chr AAEX03025924.1
		Switch Chr AAEX03025925.1
		Switch Chr AAEX03025926.1
		Switch Chr AAEX03025927.1
		Switch Chr AAEX03025933.1
		Switch Chr AAEX03025944.1
		Switch Chr AAEX03025953.1
		Switch Chr AAEX03025959.1
		Switch Chr AAEX03025975.1
		Switch Chr AAEX03025980.1
		Switch Chr AAEX03025991.1
		Switch Chr AAEX03025992.1
		Switch Chr AAEX03026004.1
		Switch Chr AAEX03026011.1
		Switch Chr AAEX03026013.1
		Switch Chr AAEX03026022.1
		Switch Chr AAEX03026065.1
	Finalizing  ..
